### ISSUE TITLE
translated strings are concatenated instead of tokenized/interpolated

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#1622] opened 2017-08-04 11:41 UTC
Translated strings should always use tokens instead of concatenating translated strings in a fixed order.

**Comment by bnchdrff** [comment] 2018-02-16 22:20
dupe of #2349

**Comment by sneak** [comment] 2018-02-19 01:09
cc @goldibex

**Comment by goldibex** [comment] 2018-02-19 17:12
Dupe #2349

**Closed by goldibex** 2018-02-19 17:12 UTC
Labels: i18n, needs-review
