### ISSUE TITLE
The ≡ (three lines) vs the user icon is confusing.

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#1105] opened 2017-02-04 19:14 UTC
I haven't figured out an obvious alternative yet, but still to this day I end up clicking the 3 bar icon instead of the little face icon by mistake about 1/3 of the time.

The more I look at what's under the ≡, the less it make sense. This menu can best be defined as a clusterfuck.

I think this hole mess of FAQ, Whitepaper, and Change you password, could be under a "More" Section under the user setting

Quick review:

    About (static no need to access after login)
    Explore (Wrong title, Just a list of tags)
    Steemit Whitepaper (long and outdated)
    Welcome (Welcome what ?) Suggest "Intro" or Welcome page
    FAQ
    Buy Steem, (There are dozens of ways to buy Steem, this page is way to biased) BTW Shapeshift is much cheaper.

    Steemit App Center 
    Currency Market
    Stolen Accounts Recovery (should be in the login panel ?)
    Change Account Password (this is already in the user menu)
    Steemit Chat
    Steemit API Docs (very few people need to access this)
    Vote for Witnesses 

    Privacy Policy
    Terms of Service

I an option would be to change the way this menu look before and after the users are logged in.

I would also consider action items to be next to each other and identified with a different color or shade.

**Comment by TimCliff** [comment] 2017-02-04 19:44
There was some related discussion here: https://github.com/steemit/steemit.com/issues/614

**Comment by abitmore** [comment] 2017-02-04 20:26
AFAIK the "buy steem" feature is there so users can buy from Steemit Inc. directly (via blocktrades).

**Comment by roadscape** [comment] 2017-07-20 20:15
There's been a few adjustments to the menu since this issue was created. Can it be closed?

**Comment by plink01001** [comment] 2017-11-14 03:43
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:43 UTC
Labels: enhancement-review, suggestions/feedback, UI
