### ISSUE TITLE
It would be nice to be able to see everything I upvoted like the comments and replies

### ISSUE THREAD

**Issue by wildajet** [steemit/condenser#1942] opened 2017-11-07 20:52 UTC
It would be nice to have a tab to be able to see everything I've upvoted.  Just like I can see all my comments and the replies to comments or posts.

**Comment by TimCliff** [comment] 2017-11-07 23:02
@wildajet - it is a good suggestion, but please read the [guidelines for contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md) before opening issues.

![image](https://user-images.githubusercontent.com/20735105/32522541-58815974-c3dd-11e7-984a-03be082a6786.png)

@sneak to close.

**Comment by plink01001** [comment] 2017-11-16 02:57
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:57 UTC
Labels: enhancement-review
