### ISSUE TITLE
Front-end image cache prevents update

### ISSUE THREAD

**Issue by VIM-Arcange** [steemit/condenser#1107] opened 2017-02-06 10:33 UTC
When user publish an image in a post, the image URL becomes prefixed with
`https://steemitimages.com/0x0/`

This allows images to be resized by the front-end but also means images are cached/proxied

If, for any reason the target image change, it is not updated in the post.
This prevents to embed dynamic images from external sources in posts.

Before showing image, the front-end should check if the image `Last-Modified` attribute has changed.
In this case, it should reload the image from source instead from cache.

Another solution is to allow the user "to self-prefix" the image in markdown with something like:
`https://steemitimages.com/[width]x[heigth]x[cache timeout in minutes]/`
This would avoid the front-end to check for image attribute too often.

**Comment by VIM-Arcange** [comment] 2017-05-05 00:34
Any update on this issue?
This has been implemented and put in production on golos.io and it is very useful.

**Comment by relativityboy** [comment] 2017-09-08 16:42
Interesting. This might be a bit less secure than using the proxy.

**Comment by roadscape** [comment] 2017-09-08 18:33
Currently dynamic images are not a supported use case. Sometimes images are taken down or replaced; current behavior is to preserve the original. In this sense the proxy is more of an archive. I'm not sure the benefits outweigh the complexity.

**Comment by VIM-Arcange** [comment] 2017-09-11 16:08
@roadscape the main reason for this request is for [SteemitBoard](https://steemit.com/steemitboard/@steemitboard/steemitboard-the-steemit-gamification-experience) (see section "Using your awards in your posts to impress your friends").  People want to add their awards in their post.

Actually, the proxy/cache prevent using the described methodology and users have to host a copy of their awards somewhere else before adding them in a post. Really annoying as awards may be updated often, especially for new users.

The Golos devs have added "proxy bypass" feature for months. It is working perfectly and really appreciated buy users. Maybe you should contact them to have more info on how they implemented it.

**Comment by plink01001** [comment] 2017-11-14 03:43
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:43 UTC
Labels: enhancement-review, feature-request

**Comment by corkyk** [comment] 2018-05-03 12:41
Bump, I too have a use case for allowing images to be updated after the edit window closes. Just throwing my hat in the ring for this proxy/cdn bypass to be implemented for the creation of more useful apps.
