### ISSUE TITLE
Can we get the subtitle cut a little shorter?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#1135] opened 2017-02-09 16:32 UTC
If we could get the subtitle to stop at the second punctuation that would clean them up a little.

This arbitrary number it is currently on makes it difficult to subtitle a post with accuracy.

**Comment by mcifani** [comment] 2017-02-10 14:58
@FreeBornAngel Thanks for your suggestion, could you please be more specific/which subtitle view your referring.  In regards to the post previews snippets they cut by length not punctuation.

**Comment by FreeBornAngel** [comment] 2017-02-10 23:52
Yes.
When viewing a post in the feed, one sees the title followed by a subtitle of x spaces.
I've never counted how many spaces are given for the subtitle.

I would like to change that from x spaces to the second punctuation.

The randomness of my sentences makes for subtitles less than optimal.
With the end coming at the second punctuation mark I can know what will be contained in the subtitle and work with that.

**Comment by mcifani** [comment] 2017-02-11 23:21
Regardless of how the subtile/preview text is displayed it's important that 1. It will continue to be truncated with (...) or with some verbiage ('read more') etc.  It's important the viewer doesn't feel they have read the entire post when more content is available.  As for when it's cut - I'm not certain if having it as requested is best, as it could change the dynamic with subtitles instead of preview of the content with less precision.

**Comment by pfunks** [comment] 2017-02-13 06:17
Is there a reason there isn't a user-specified subtitle by now? Having formatting like the subtitle and preview/thumbnail image forced by whatever image and text comes first is getting stale.

**Comment by mcifani** [comment] 2017-02-13 16:55
@pfunks It's an interesting concept but needs further discussion and prioritized(if it seems like the correct route) @sneak

**Comment by roadscape** [comment] 2017-07-21 18:26
Right now it tries to pick an optimal length, and chops to punctuation if it can. The UI has the ability to truncate it further if it's a particularly narrow screen.

We could add another rule: if there is a period followed by 2 spaces, it will try to truncate there.

**Comment by plink01001** [comment] 2017-11-14 03:45
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:45 UTC
Labels: enhancement, enhancement-review, small+quick win, UI
