### ISSUE TITLE
Delete / edit a post

### ISSUE THREAD

**Issue by Broxkrak** [steemit/condenser#2162] opened 2017-12-15 04:17 UTC
A big issue that steemit can not delete / editing a earlier post. I know few people having nightmares because there post are shown in steemit / google by writing their personal information. It will always be on blockchain history, but it should be possible to delete or edit  it from the public. It can be dangerous for the person if he's / her past always are visible.

**Comment by plink01001** [comment] 2018-03-06 02:28
duplicate of https://github.com/steemit/condenser/issues/1373

**Closed by plink01001** 2018-03-06 02:28 UTC
