### ISSUE TITLE
Ability to use scroll wheel to adjust vote slider

### ISSUE THREAD

**Issue by liondani** [steemit/condenser#169] opened 2016-08-23 14:57 UTC
![screenshot from 2016-08-23 17 55  #34](https://cloud.githubusercontent.com/assets/6908400/17896885/d844823c-695a-11e6-9184-6a459c523394.png)

It would increase user experience if when voting with the vote-slider we could change the voting % by scrolling the mouse wheel up or down (Up to 100 down to 0)

![mouse-scroll-wheel](https://cloud.githubusercontent.com/assets/6908400/17896836/aa34fcd2-695a-11e6-9466-f5229598400d.jpg)

**Comment by roadscape** [comment] 2017-07-21 18:47
@TheIntrnet if this is straightforward to add, let's do it. Otherwise please close the ticket.

**Comment by plink01001** [comment] 2017-11-14 03:09
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:09 UTC
Labels: enhancement-review, nicetohave, small+quick win
