### ISSUE TITLE
Feature Request: Spoiler tags

### ISSUE THREAD

**Issue by arhag** [steemit/condenser#8] opened 2016-05-19 21:21 UTC
Categories on Steem like [this one](https://steemit.com/got/@hcf27/game-of-thrones-discussion) are really going to want spoiler tags rendered on Steemit.
The format would be something like this:

```
[Visible text warning readers of the scope of the spoiler goes here](#some-spoiler-tag "Actual spoiler content goes here")
```

And steemit would be responsible for identifying the correct spoiler tag through the fragment identifier on the link (`#some-spoiler-tag` in the example above). Technically each channel could have its own CSS (that's a whole other proposal though!) to identify and render different fragment identifiers in different ways like reddit does. But the simpler solution is to make #spoiler be the standard fragment identifier that the Steemit website recognizes and renders properly. To see an example of spoiler tags in action, click [here](https://www.reddit.com/r/gameofthrones/wiki/spoiler_guide#wiki_how_to_make_spoiler_tags).

**Comment by roadscape** [comment] 2016-09-15 14:50
How about `<span class="spoiler">soylent green is people</span>`?

It would be easier to support across various UI's than by extending markdown.

**Comment by arhag** [comment] 2016-09-15 20:19
> How about `<span class="spoiler">soylent green is people</span>`?

That's (almost) fine with me, but you need to whitelist the class names allowed for a span otherwise people could find clever ways of abusing it using existing CSS styles provided by the website. And I say almost because I think it would be very useful to have a way of specifying some text that is visible by default. Once again check the side bar in page I linked to above to see examples of what I mean. It should be easy for the reader to see what book/episode/whatever they need to be caught up with in order to be confident that hovering over the text to reveal the hidden content won't spoil anything for them. Could we perhaps allow a custom attribute to the tag, such as `warning` which contains as its value that warning text?

For example:
`<span class="spoiler" warning="GoT S06E05">Hold the door : (</span>`

**Comment by roadscape** [comment] 2016-09-15 20:34
There is a strict whitelist of which tags can use which classes (and which tags can have classes, etc)

I would prefer to stay away from adding custom HTML attributes for the sake of simplicity, at least for the first iteration. Imho, your example could be served just as well using `S06E05:<span class="spoiler">Hold the door : (</span>` -- it's not as elegant but it's trivial for any frontend to implement. ([example](https://jsfiddle.net/ks4vkt2s/))

Alternatively, we could co-opt the `<del>` tag. This is more "visually appropriate" in that `<del>` creates a strikethrough by default. ([example](https://jsfiddle.net/u6w3q0t2/2/))

Or, we just use a `<spoiler>` tag. IIRC nowadays you can name your elements whatever you want. Maybe this is the friendliest solution overall ([example](https://jsfiddle.net/9rvb4h8n/1/))

**Comment by arhag** [comment] 2016-09-15 21:00
I don't like abusing the semantics of the `<del>` tag. I do like using a custom `<spoiler>` tag rather than a generic `<span>`.

So how about this: https://jsfiddle.net/t2xs3dqx/

So even if the CSS doesn't load, you can still understand the content properly without any weird insertions into the text for the warning labels, and same goes for the text that is selected, copied, and pasted.

**Comment by plink01001** [comment] 2017-11-14 02:57
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 02:57 UTC
Labels: enhancement, enhancement-review, feature-request, priority/low
