### ISSUE TITLE
font text changes to white on one of the text editor menus on the post page

### ISSUE THREAD

**Issue by kodeblacc** [steemit/condenser#2669] opened 2018-03-17 00:24 UTC
#### Expected behavior
I expected that when I'm on Night mode the text editor panel will still contain black fonts because night mode or not the post page doesn't change colour.

#### Actual behavior
On Night mode, texts in one editor menu displays white fonts which makes it impossible to see when on night mode.

#### How to reproduce

- login into steemit
- change to Night mode and the font text on one of the text editor panel  changes to white

* Browser:  google chrome
* Operating system: windows 7 proffesional

#### Recording Of The Bug
https://youtu.be/Lq4CDGXOghQ

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@kodeblacc/font-text-changes-to-white-on-one-of-the-text-editor-menus-on-the-post-page">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by roadscape** [comment] 2018-04-18 19:27
@kodeblacc does this issue persist for you on steemit.com? I cannot reproduce locally.

**Comment by kodeblacc** [comment] 2018-04-18 19:31
Yea check the video in the report

**Comment by roadscape** [comment] 2018-04-18 19:43
Thanks, I saw the video, just wanted to make sure it was not addressed by some other work since it was reported.

**Comment by kodeblacc** [comment] 2018-04-18 19:45
Oh okay

**Closed** 2018-04-19 17:27 UTC
Labels: 1, bug
