### ISSUE TITLE
"RPCError: Assert Exception:o.weight != 0: Vote weight cannot be 0." - Can't vote at 100% (w/o changing it before clicking). Can vote 98%.

### ISSUE THREAD

**Issue by royachiron** [steemit/condenser#2926] opened 2018-07-03 15:54 UTC
See gif. My VP was good, 98 worked. 

![56](https://user-images.githubusercontent.com/23020420/42230253-31c44e70-7ef1-11e8-858f-251c21c64e81.gif)

On a sidenote, the entire slider mechanism is bad UI IMO. You would do good to get rid of it, or change it so it doesn't just pop up when the vote button is clicked. Instead of clicking a post to vote, I  now need anywhere between 2 to 10 mouse operations, considering how fine tuning of the VP is not possible.

**Comment by roadscape** [comment] 2018-07-16 18:35
@royachiron what do you mean by "fine tuning of the VP is not possible"? The slider should only appear when your SP is above a certain level.

**Comment by royachiron** [comment] 2018-07-16 18:50
@roadscape using a mouse to set it to a specific number is hard. Think of this 0-100 slider as 101 tiny buttons, now you get it? And please if you do any change, just make this 2 click nightmare go away please.

**Comment by royachiron** [comment] 2018-07-16 19:50
@roadscape I get the idea, it's just bad UX I'm sorry to say. IMO, make it into 2 buttons, one to vote, and next to it, in English there will be a button named "change vote power". The upvote button will always be 1 click operation.

**Comment by TimCliff** [comment] 2018-07-19 17:19
dupe of https://github.com/steemit/condenser/issues/2920

**Closed** 2018-07-23 19:49 UTC
Labels: 3, bug
