### ISSUE TITLE
Adding code formatting support

### ISSUE THREAD

**Issue by VMois** [steemit/condenser#2962] opened 2018-07-28 23:36 UTC
Do you plan to add any code formatting support (JS, python etc.) for Markdown? Thanks.

**Comment by VMois** [comment] 2018-07-28 23:41
For example, integrate https://highlightjs.org/ library. Is it possible?

**Comment by roadscape** [comment] 2019-04-23 19:55
Dupe of https://github.com/steemit/condenser/issues/2095

**Closed by roadscape** 2019-04-23 19:55 UTC
