### ISSUE TITLE
Please allow hearthis.at embeds.

### ISSUE THREAD

**Issue by ekollof** [steemit/condenser#1694] opened 2017-08-31 08:34 UTC
heathis.at is a relatively new music service (alternative to soundcloud). Right now it doesn't embed inside Steemit. Could it be added?

Example embed from hearthis.at:

```
<iframe scrolling="no" id="hearthis_at_track_1348613" width="100%" height="150" src="https://hearthis.at/embed/1348613/transparent_black/?hcolor=&color=&style=2&block_size=2&block_space=1&background=1&waveform=0&cover=0&autoplay=0&css=" frameborder="0" allowtransparency><p>Listen to <a href="https://hearthis.at/nft4crvb/wings-of-hatred-testmaster6/" target="_blank">Ninth Circle Alliance - Wings of Hatred</a> <span>by</span><a href="https://hearthis.at/nft4crvb/" target="_blank" >Emiel Kollof</a> <span>on</span> <a href="https://hearthis.at/" target="_blank">hearthis.at</a></p></iframe>
```

**Comment by plink01001** [comment] 2017-11-15 04:18
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:18 UTC
Labels: enhancement-review
