### ISSUE TITLE
Lock the comment sort on load

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#682] opened 2016-11-21 10:21 UTC
When upvoting change the order of the posts in the page the position is lost suddenly.

**Comment by roadscape** [comment] 2016-11-21 15:06
Are you referring to comments?

**Comment by Transisto** [comment] 2016-11-22 23:50
Yes

**Comment by jcalfee** [comment] 2016-11-28 21:24
Your vote may have affected the trending order.  I did a test vote that did not change the blockchain and the order did not change.   I'm going to start watching this:  After a vote, refresh to see if the comment order is accurate.

**Comment by roadscape** [comment] 2016-12-01 16:51
Yep, the issue is that comments are sorted by pending payout and casting a vote will make it jump up the list.

**Comment by svk31** [comment] 2016-12-01 18:29
This is intended behaviour as far as I can tell, but it might be a good idea to add an animation to show the reordering that happens.

**Comment by jcalfee** [comment] 2016-12-01 18:42
Aside from being a challenge to our architecture, can you think of any downside to making the sort order based on a something like a clone?  That would update only if the order or navigation changes.

**Comment by jcalfee** [comment] 2016-12-01 18:44
In my experience it is more often that I would want to remain in the thread and not have to worry about voting the tree from the inside out so I don't lose my place.  It is very rare that I would want to see the sort order after I vote so that would be better if that were more manual.

**Comment by relativityboy** [comment] 2017-08-25 16:15
@roadscape @jcalfee @svk31 @Transisto 
I think having the sort order be fixed once the page loads is far more usable. Maybe @ some point in the future we add a toggle for 'stable/reading' and 'dashboard/live' views.

Does locking the sort on load sound good? (High effort or low?)

**Comment by roadscape** [comment] 2017-08-25 16:19
@relativityboy fixed is fine. If a user wants to see new rankings she can F5.

**Comment by plink01001** [comment] 2017-11-14 03:29
Are there plans to make any changes for this issue, or should it be closed?

**Comment by plink01001** [comment] 2017-11-28 01:17
This issue may be good to solve at the same time: https://github.com/steemit/condenser/issues/421

**Comment by pkattera** [comment] 2018-09-07 18:41
Looks like this interaction has the expected behavior:
Essentially, on upvote, the comments dynamically update, and the user is still able to see the comment they voted on (even if it changed position).
I'm not sure if it has been fixed since the initial issue was created.

**Closed by pkattera** 2018-09-07 18:41 UTC
Labels: bug
