### ISSUE TITLE
Allow user-provided anchor links & targets

### ISSUE THREAD

**Issue by igorterleg** [steemit/condenser#205] opened 2016-08-31 05:53 UTC
Internal links in steemit posts (at least put in raw html) are prepended with "https://" which makes it impossible to e.g. add footnotes to articles or link to other sections.

I think it might be [this issue](https://github.com/steemit/steemit.com/issues/152)'s solution taken a little too far. 

An example can be seen [here](https://steemit.com/test/@igorterleg/another-test-please-ignore), where "internal link" should be "#id1" and thus target "link target" but is "https:///#id1" instead.

**Comment by jcalfee** [comment] 2016-08-31 12:53
The test code from the post:
```
<a href="#id1">internal link</a>
<div id="#id1">link target<div>
```

**Comment by igorterleg** [comment] 2016-08-31 18:59
I made a mistake there, should be div id="id1" obviously.

**Comment by igorterleg** [comment] 2016-09-03 08:44
It also removes the ```id``` attribute from the link target.

This is the code input:

```html
<a href="#id1">internal link</a>

<div id="id1">link target<div>
```

and this the html generated:
```html
<div><p><a href="https://#id1" rel="nofollow noopener">internal link</a></p>
<div></div>link target<div></div>
```

**Comment by jcalfee** [comment] 2016-09-06 14:48
@roadscape I'm not sure about your original use cases in the regex used to suffix https://.. so I don't want to change that part without our going over it.

**Comment by jcalfee** [comment] 2016-09-09 01:41
@roadscape another case here.. The first image in the post:

https://steemit.com/drugs/@aggroed/how-i-became-the-first-steemitmillionaire

has this:

<img src="//www.heartti.com/wp-content/uploads/2016/05/dollar-in-a-bag.jpg" />

which renders as a broken image like this:

https://img1.steemit.com/0x0///www.8asians.com/wp-content/uploads/2011/10/china_breasts_art-600x400.jpg

**Comment by roadscape** [comment] 2016-09-09 16:18
@igorterleg an issue with user-generated id attributes is that they belong to a global namespace. 

This can result in conflicts when a UI relies on unique id's for styling and javascript functionality.

One solution would be to enforce user-generated `id`s to always use a specific prefix. This could be done automatically in sanitize. The prefixes may need to be unique per post. Otherwise comments could conflict with anchors in the top level post.

(this is also relevant to #221)

**Comment by igorterleg** [comment] 2016-09-09 16:58
Well I don't think it would be a problem if sanitize altered these ids in any way, as long as hrefs in links would be also altered so that the links are not broken.

**Comment by jcalfee** [comment] 2016-09-09 17:10
I feel like the id and https:// prefix is mixing two topics.  O well.  Two very good ideas you have there... 

Lets think about other sites that render the html too.  We could use a namespace (prefix) and block any post that tries to save using that namespace and prevent rendering with that prefix unless it is our anchor.  This way most of html is good to go without any modification or special rules.

**Comment by roadscape** [comment] 2016-09-15 18:47
> Well I don't think it would be a problem if sanitize altered these ids in any way, as long as hrefs in links would be also altered so that the links are not broken.

Yep, exactly. 

User-provided `<div id="xxx">`'s and `<a href="#xxx">`'s will need the `xxx` to be prefixed with `author_permlink` to avoid conflicts with other posts and app elements on the page.

**Comment by joshuadanpeterson** [comment] 2017-08-28 23:20
Has much progress been made on this front? I posted about the anchor linking issue on my Steemit account: https://steemit.com/steemit-bug/@joshpeterson/steemit-bug-report-broken-anchor-links But I also wanted to make sure that you all saw it. Thanks again, for all of your work.

**Comment by sneak** [comment] 2017-08-29 00:27
It's pretty low priority at this point; we are working on several major features in condenser and this is on our radar but doesn't have any deadline or resources allocated at the moment. It's not a do-or-die right now, unfortunately.

**Comment by joshuadanpeterson** [comment] 2017-08-29 05:21
Okay, thanks for your response, @sneak. Looking forward to the update.

**Comment by plink01001** [comment] 2017-11-14 03:11
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:11 UTC
Labels: enhancement, enhancement-review

**Comment by DpdC** [comment] 2018-04-20 15:47
Well, man. If an application that works with html and markdown. It does not execute either of them correctly. And decide that this problem does not have priority.

Because this problem shows that the code is not running correctly. The anchors should work in at least one of its two forms, with HTML, or with Markdown.

I do not know what is the priority. It has an application based on an editor, which does not correctly execute the code. It has been warned of almost 2 years ago, and it is not a priority... 

If you are interested, I inform you that is still broken.

Although I have no hope that they will review it, since I see. That you are not interested in fixing it and directly close all related entries..

I'll have to know how to live without them (anchors).

**Comment by roadscape** [comment] 2018-04-20 15:59
@DpdC the concerns have been outlined above; it seems there may be conflicts if we allow user-generated id's. We could potentially have a strict filter and/or blacklist for reserved names but edge cases need to be accounted for. If you have any suggestions to share or want to submit a PR please do!

**Comment by DpdC** [comment] 2018-04-20 16:56
@roadscape I'm not a professional, so I can help you. Unfortunately.
I have noticed that also the method of references that markdown uses does not work. ( [example][1] for [1]: https___  )
I understand that it is due to the same? There is no possibility of creating internal links? :(

I'm sorry, for my words. Writing in hot is never good. Thanks for the work on the platform ..

**Comment by dfroberg** [comment] 2018-12-14 14:04
Would be great if this issue could be reopened.
Requiring prefixes would solve GUI conflicts but would make 99.999% users utterly confused, 
Would be easier to prefix all internal ids and expressly filter those ids that matches the prefix.
That'd give the content creators their freedom and securing the platform.
