### ISSUE TITLE
Followers and Followed not showing

### ISSUE THREAD

**Issue by tourdefran** [steemit/condenser#2198] opened 2017-12-20 19:59 UTC
In your profile page the Followers button doesn't retrieve your info. The bug is present also in the Followed section

![image](https://user-images.githubusercontent.com/2666701/34225942-e7ffcff0-e5a6-11e7-8432-1f63b45f985d.png)

![image](https://user-images.githubusercontent.com/2666701/34225977-fd8fc38e-e5a6-11e7-9d00-fb64238a1718.png)

**Comment by gl2748** [comment] 2017-12-20 20:00
@tourdefran thanks for this. There is a fix in the process of being deployed. Thanks.
duplicate of  #2191

**Closed by gl2748** 2017-12-20 20:00 UTC
