### ISSUE TITLE
Audit config system & document how it works

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#1828] opened 2017-10-20 15:25 UTC
as a new dev, i wanted to easily provide config settings to use a testnet (as an example) but it didn't work as was described in the project docs.

i expected to be able to edit a config file, but i ended up having to supply env vars at runtime.

to make dev life easier, we should remove unused config files, clarify how the required ones are used, and provide examples for common config tasks such as overriding in the dev environment, modifying config when deploying, and adding new config items.

**Comment by plink01001** [comment] 2017-11-16 02:20
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:20 UTC
Labels: enhancement-review
