### ISSUE TITLE
Profile picture upload should be done through the imagehoster.

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1384] opened 2017-04-30 14:12 UTC
When setting a profile picture condenser prompts you to enter a URL for a profile picture. It should instead prompt to upload a photo through the imagehoster, the same as the drag and drop feature works. However this is implemented it should also make sense on mobile.

**Comment by roadscape** [comment] 2017-07-20 18:53
Dupe of https://github.com/steemit/condenser/issues/1303

**Closed by roadscape** 2017-07-20 18:53 UTC
