### ISSUE TITLE
7 day trending page and 24 hours trending page. 

### ISSUE THREAD

**Issue by Team-Steem** [steemit/condenser#1315] opened 2017-04-08 00:50 UTC
I read around 50-100 titles articles a day around the web and on Steemit.Making me re-reading the same titles over and over is killing the novelty seeking pleasure and a lost of time. 2 days old articles don't have their place on the trending page. We've had time to read them 4 days already. There's definitely a need for a 7 days old trending page.

**Comment by TimCliff** [comment] 2017-04-17 14:30
This seems like a duplicate issue with https://github.com/steemit/condenser/issues/1297

**Comment by roadscape** [comment] 2017-04-19 17:15
Dupe of #1297

**Closed by roadscape** 2017-04-19 17:15 UTC
