### ISSUE TITLE
Can't Register New Account - Please Help FIX

### ISSUE THREAD

**Issue by shammin** [steemit/condenser#1362] opened 2017-04-23 19:10 UTC
Couldn't create account. Server returned the following error:
10 assert_exception: Assert Exception creator.vesting_shares - creator.delegated_vesting_shares - asset( creator.to_withdraw - creator.withdrawn, VESTS_SYMBOL ) >= o.delegation: Insufficient vesting shares to delegate to new account. {"creator.vesting_shares":"1470460571.544648 VESTS","creator.delegated_vesting_shares":"1470260000.000000 VESTS","required":"220000.000000 VESTS"} th_a steem_evaluator.cpp:206 do_apply {"op":["account_create_with_delegation",{"fee":"9.000 STEEM","delegation":"220000.000000 VESTS","creator":"steem","new_account_name":"deadmanschest","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM81FTszFtGX9EnF82QSXVgx9tsG7yfTCXU1zKg3B31Fq8tdMynx",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72VnneiqjDmcMzQBgHvKV9QPa9C1W5MjspqWDebPvCtk8h8uYN",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7mrER4GpV6XwxpFhLHbzWey6WobPGUa84A1a4xUEP3Xio9j4R4",1]]},"memo_key":"STM5fNBwRh4xTins44vxpw7NAKjoHCgx1ZvSpEqenqVW4tywtjwf6","json_metadata":"","extensions":[]}]} th_a database.cpp:2990 _apply_transaction {"trx":{"ref_block_num":52730,"ref_block_prefix":867737285,"expiration":"2017-04-23T19:06:06","operations":[["account_create_with_delegation",{"fee":"9.000 STEEM","delegation":"220000.000000 VESTS","creator":"steem","new_account_name":"deadmanschest","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM81FTszFtGX9EnF82QSXVgx9tsG7yfTCXU1zKg3B31Fq8tdMynx",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72VnneiqjDmcMzQBgHvKV9QPa9C1W5MjspqWDebPvCtk8h8uYN",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7mrER4GpV6XwxpFhLHbzWey6WobPGUa84A1a4xUEP3Xio9j4R4",1]]},"memo_key":"STM5fNBwRh4xTins44vxpw7NAKjoHCgx1ZvSpEqenqVW4tywtjwf6","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2019b2f45aac22a7dabc91d8912423a520045349cb4d747abba64b6397efade784766d718894ffe3658bd04f439b6dbca264b3def5992760327ed4bba7740c3745"]}} th_a database.cpp:2994 _apply_transaction {"trx":{"ref_block_num":52730,"ref_block_prefix":867737285,"expiration":"2017-04-23T19:06:06","operations":[["account_create_with_delegation",{"fee":"9.000 STEEM","delegation":"220000.000000 VESTS","creator":"steem","new_account_name":"deadmanschest","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM81FTszFtGX9EnF82QSXVgx9tsG7yfTCXU1zKg3B31Fq8tdMynx",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72VnneiqjDmcMzQBgHvKV9QPa9C1W5MjspqWDebPvCtk8h8uYN",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7mrER4GpV6XwxpFhLHbzWey6WobPGUa84A1a4xUEP3Xio9j4R4",1]]},"memo_key":"STM5fNBwRh4xTins44vxpw7NAKjoHCgx1ZvSpEqenqVW4tywtjwf6","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2019b2f45aac22a7dabc91d8912423a520045349cb4d747abba64b6397efade784766d718894ffe3658bd04f439b6dbca264b3def5992760327ed4bba7740c3745"]}} th_a database.cpp:735 push_transaction {"call.method":"call","call.params":[3,"broadcast_transaction_with_callback",[null,{"ref_block_num":52730,"ref_block_prefix":867737285,"expiration":"2017-04-23T19:06:06","operations":[["account_create_with_delegation",{"fee":"9.000 STEEM","delegation":"220000.000000 VESTS","creator":"steem","new_account_name":"deadmanschest","owner":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM81FTszFtGX9EnF82QSXVgx9tsG7yfTCXU1zKg3B31Fq8tdMynx",1]]},"active":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM72VnneiqjDmcMzQBgHvKV9QPa9C1W5MjspqWDebPvCtk8h8uYN",1]]},"posting":{"weight_threshold":1,"account_auths":[],"key_auths":[["STM7mrER4GpV6XwxpFhLHbzWey6WobPGUa84A1a4xUEP3Xio9j4R4",1]]},"memo_key":"STM5fNBwRh4xTins44vxpw7NAKjoHCgx1ZvSpEqenqVW4tywtjwf6","json_metadata":"","extensions":[]}]],"extensions":[],"signatures":["2019b2f45aac22a7dabc91d8912423a520045349cb4d747abba64b6397efade784766d718894ffe3658bd04f439b6dbca264b3def5992760327ed4bba7740c3745"]}]]} th_a websocket_api.cpp:124 on_message (see err.payload for the full error payload

**Comment by steevc** [comment] 2017-04-26 07:52
Duplicate of this issue https://github.com/steemit/condenser/issues/1340

The Steem account is running out of SP to delegate

**Closed** 2017-04-26 08:55 UTC
