### ISSUE TITLE
Add the tag "tags" as first and the post is not shown

### ISSUE THREAD

**Issue by wehmoen** [steemit/condenser#3082] opened 2018-11-02 11:21 UTC
When you add the tag "tags" as the first tag to your post you can not open it on steemit.com.

https://steemit.com/tags/@guest123/3pa2rv-test

**Comment by pkattera** [comment] 2018-11-02 19:11
I can confirm, I'm getting the same error. 

After posting with a tag of "tags", the URL goes to a 404 page error. 

I wonder if "tags" is a special term that has been reserved for for https://steemit.com/tags ?

**Comment by wehmoen** [comment] 2018-11-03 12:28
I think so. I also tried the tags "trending" and "market" but they work fine.

**Comment by roadscape** [comment] 2019-04-23 20:10
`/tags` route regex needs to be fixed

**Comment by quochuy** [comment] 2019-05-10 09:50
@roadscape looks like it's already been fixed? Can't reproduce it.

**Comment by roadscape** [comment] 2019-05-13 15:49
Aha good catch. It was probably resolved with hivemind API. Closing.

**Closed by roadscape** 2019-05-13 15:49 UTC
Labels: bug, help-wanted, small+quick win
