### ISSUE TITLE
Steemit Design Update - Justifying the Content Box

### ISSUE THREAD

**Issue by deveerei** [steemit/condenser#1906] opened 2017-11-01 11:00 UTC
<center>
![aaaa.gif](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509532136/nr0llxnfst0xytjgufjh.gif)
</center>

What you see here is Steemit's pop-up content box. This opens when you click on a post or reply/comment in desktop view. 

![1.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509526483/scg2l347z8un4mscbryg.png)

I think that this feature needs improvement. There are a few things I can suggest they make changes to. To justify my suggestions, take a look at the same page in mobile view:

![2.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509526571/uzxkhpuacolxdradoycw.png)

### <center> What's the difference? It's symmetry and alignment! </center> <h3>

I made this mock-up of the same page, only it has a more symmetrical design than the original. The text box and the white post-information box at the top has been made into the same size.

The information about the author of that comment and the comment itself has been justified to the left and the timestamp has been justified to the right.

The **"Post"** and **"Cancel"** buttons have been made the same size and has been properly aligned.

I also applied [my previous suggestion](https://steemit.com/utopian-io/@deveerei/steemit-design-update-a-borderline-idea) about the shadow becoming a border.

![3.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509527384/vyz67czzwfnismueqpoy.png)

Here's a look at a side-by-side comparison of the two: The Original/Current Design V.S. The Revised Justified Design:

![4.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509527377/lkbj04eha6cn9jkpyklj.png)

I added guidelines to show you that the elements do not have symmetry at all. You can see it through the lines I placed on the right panel, it shows the alignment and position of those elements. While on the left panel, I was able to use less lines that means it's more symmetrical and are properly aligned.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@deveerei/steemit-design-update-justifying-the-content-box">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment] 2017-11-16 02:39
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:39 UTC
Labels: enhancement-review
