### ISSUE TITLE
Wallet page doesn't refresh or show complete transaction history

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#2969] opened 2018-08-03 05:09 UTC
Frequently the wallet page will not show all transactions, or only a few will load.  In some cases, no transactions will load.  Loading the wallet page on any user (especially those with lots of operations on their account) is kind of a like a box of chocolates.  You never know what you are going to get.

The wallet page is the most important page on Steemit for 99% of the users. It should be reliable, and trustworthy.

**Comment by plink01001** [comment] 2018-08-09 21:15
There are two parts to this: recent transactions not showing up, and old transactions not showing up. 

Currently the steemit.com wallet page does not show historic transactions after a certain point. This is not an urgent concern, although it is on the radar. For now, users can use alternate UIs such as steemdb.com if they are interested in seeing historic data.

For the recent transactions not showing, this is likely a duplicate of https://github.com/steemit/condenser/issues/2900, and something we are addressing in pull request https://github.com/steemit/condenser/pull/2973.

**Closed by plink01001** 2018-08-09 21:15 UTC
