### ISSUE TITLE
Resteem on comments

### ISSUE THREAD

**Issue by psoscrypto** [steemit/condenser#2994] opened 2018-08-24 22:09 UTC
When you access to repleis option and click on a replei there is a resteem button that generate an error if you try to resteem that comment

**Comment by relativityboy** [comment] 2018-10-22 15:42
@psoscrypto - can you provide a screenshot with the error?

**Comment by psoscrypto** [comment] 2018-10-22 20:47
![img_20181022_214434_645](https://user-images.githubusercontent.com/42246415/47318472-0e401100-d644-11e8-9788-3e88087bb4ec.JPG)

**Comment by quochuy** [comment] 2019-05-23 08:35
@roadscape
I can't reproduce this neither in desktop or mobile browser.
The resteem button does not show up.

The code confirms it too (Reblog.jsx):
`    render() {
        if (this.props.author == this.props.account || this.props.parent_author)
            return null;`

**Comment by roadscape** [comment] 2019-05-28 18:13
Thanks for looking into this @quochuy! Closing.

**Closed by roadscape** 2019-05-28 18:13 UTC
Labels: bug, needs-review
