### ISSUE TITLE
Clarify post payouts and the curator reward share

### ISSUE THREAD

**Issue by liondani** [steemit/condenser#87] opened 2016-07-30 03:05 UTC
https://steemit.com/steemit/@jholdsworthy/why-does-the-payout-of-a-post-go-down-directly-when-it-s-paid-out

https://steemit.com/steemit/@anduweb/is-there-something-wrong-with-the-payout-amount-calculation-before-the-payout-moment-big-difference-between-the-two

https://steemit.com/retention/@timcliff/important-why-steemit-needs-to-change-the-way-pending-payments-are-displayed

Show us independently what exactly the poster will get and what the curators before the pay out's happen...
For example:
When mouse over : show what curators get, when not, show what only the poster gets in real time!

**Comment by roadscape** [comment] 2016-08-23 20:41
Changes:

1) Total shown payout will no longer drop by 25%+ upon payout (i.e. it adds curator reward back in)
2) Past payout shows the breakdown between author and curators

One other tweak to consider is to not include the curator bonuses in the shown (potential+past) payout. But this would (a) require more info from the backend, and (b) lower all shown payouts (not ideal for review). #153 may be enough to address author awareness of these rules. Thoughts?

**Comment by liondani** [comment] 2016-08-24 12:42
> One other tweak to consider is to not include the curator bonuses in the shown

why not? more info is better than less

**Comment by liondani** [comment] 2016-08-24 12:48
>may be enough to address author awareness of these rules. Thoughts?

The user's are lazy to make the math to figure out how much they will get even if they have the right instructions to do it... We must keep the logic of WYSIWYG (What you see is what you get) ...
Sorry if I probably don't understand your suggestion...

**Comment by liondani** [comment] 2016-08-24 12:50
sorry for off topic but I want your thoughts on my comment to @theoreticalbts here
https://github.com/steemit/steem/issues/267#issuecomment-241903722

**Comment by iamsmooth** [comment] 2016-08-25 06:38
@liodani 
> why not? more info is better than less

I don't think @roadscape was suggesting not to have the info available at all, but to show the author's reward as the primary (displayed by default) figure and then show both rewards in the detail. 

I could see arguments either way, but I definitely like fixing the unexpected drop after payout as @roadscape did here.

**Comment by roadscape** [comment] 2016-09-14 21:16
Related: #193

> That said, there is plenty of room for improvement in communicating these nuances to users. 
Any and all suggestions are welcome. The tricky part is adding more info to the UI without making it even more intimidating ;)

**Comment by TimCliff** [comment] 2016-09-17 02:01
I think the new display that shows the breakdown helps a lot. At least users do not think their money is disappearing!

In my opinion it could still be improved slightly by only showing the author reward as the 'potential payout'. Even with a good FAQ and tutorial, I can see new users getting confused and disappointed when they realize that they don't get to keep all of the payout themselves.

I don't know how much work this would be, but in my opinion the ideal design would be:
-Show the potential author payout as what everyone sees when they see the thumbnail payout for the post
-If the user clicks on the thumbnail to see the details, have it show both the potential author payout and potential curator payout as two separate amounts
-Keep the 'post payout summary' the same as it is today, where it shows the total payout, author payout, and curator payout as three separate numbers

**Comment by roadscape** [comment] 2016-11-06 16:36
Related: https://github.com/steemit/steem/issues/491 - API for showing author/curator split for pending payout

**Comment by roadscape** [comment] 2017-07-21 18:58
Are users still confused by this?

**Comment by TimCliff** [comment] 2017-07-22 04:43
I polled a bunch of users and got some feedback. Overall it is a *ton* better than it was when the issue was opened, but users do still have some confusion on it. The fluctuating rewards due to STEEM price changes actually seem to be a bigger issue than the author/curator split, but both do come up.

For the author/curator split showing the potential split between authors and creators during the "Pending Payout" stage would help (probably needs micro-service or something else on the back end).

An alternative that would probably solve both issues (and would be a lot easier to implement) would be some type of mouseover or other 'help' window that was tied to the potential payout that gave the user a brief blurb about how the payouts can go up/down, why, as well as the info about the author/curator split.

**Comment by plink01001** [comment] 2017-11-14 03:05
Thank you for the suggestion. We have reviewed your request and will consider implementing additional changes for this at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:05 UTC
Labels: enhancement, enhancement-review, priority/low
