### ISSUE TITLE
A post exists but it does not open on steemit.com

### ISSUE THREAD

**Issue by joticajulian** [steemit/condenser#3464] opened 2019-08-16 09:17 UTC
author: @calamus056
permlink: curation-rewards-explained-in-great-detail

When I try to open it on steemit.com it says "Sorry! This page doesnt exist."
https://steemit.com/steemit/@calamus056/curation-rewards-explained-in-great-detail
https://steemit.com/@calamus056/curation-rewards-explained-in-great-detail

However, it actually opens in the rest of front-ends:
https://steemd.com/steemit/@calamus056/curation-rewards-explained-in-great-detail
https://busy.org/@calamus056/curation-rewards-explained-in-great-detail
https://steempeak.com/@calamus056/curation-rewards-explained-in-great-detail

It is interesting to see that the author wrote in his post:
"WARNING: If the article doesn't completely load, try to refresh a few times. There seems to be a bug with this article."

**Comment by quochuy** [comment] 2019-09-04 10:44
@roadscape 
This is a duplicate of https://github.com/steemit/condenser/issues/3481 and fixed by https://github.com/steemit/condenser/pull/3482

**Comment by roadscape** [comment] 2019-09-05 12:23
Fixed in #3482

**Closed by roadscape** 2019-09-05 12:23 UTC
