### ISSUE TITLE
My communities is no longer on beta site

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#3689] opened 2020-01-26 18:27 UTC
My communities used to be on the left side sidebar, and trending communities in the right.  Now trending communities are on both sidebars.

# screenshot
https://i.imgur.com/HusyKPP.png

**Comment by roadscape** [comment] 2020-01-29 15:18
I believe this will be addressed by https://github.com/steemit/condenser/pull/3684

**Comment by gl2748** [comment] 2020-01-30 16:33
This is actually being caused by what looks like a regression
```
Error Fetching Account Subscriptions:  RPCError: Invalid Request
    at new RPCError (webpack-internal:///529:43:106)
    at eval (webpack-internal:///529:93:13)
```
Addressed in #3684

**Comment by roadscape** [comment] 2020-02-05 20:02
https://github.com/steemit/condenser/pull/3684 merged

**Closed by roadscape** 2020-02-05 20:02 UTC
Labels: bug, communities
