### ISSUE TITLE
Claim Rewards Lag - Needs Wait Indicator

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#1412] opened 2017-05-11 00:24 UTC
When users hit the button to claim rewards, it usually takes about 3 seconds. There is no progress indicator, so user's default reaction is to think nothing happened and click it again. When they do this, it gives an error. It would be good if there is some type of indication that it is working/in progress.

**Comment by roadscape** [comment] 2017-07-20 19:40
Dupe of https://github.com/steemit/condenser/issues/1311

**Closed by roadscape** 2017-07-20 19:40 UTC
Labels: priority/low, UI
