### ISSUE TITLE
Private Post (nsfw) Display Settings are outside the settings form

### ISSUE THREAD

**Issue by CryptoSharon** [steemit/condenser#2319] opened 2018-01-11 01:57 UTC
Hello, guys!

I had been trying for a few days to change my nsfw content display settings when I realized that the problem is that this setting is actually outside the form! So when we press the submit button, that specific setting is not sent to the server-side processor and it cannot be changed from the browser (I'm using Firefox, latest version).

I'll reproduce the steps for you guys :)

This is what I see when I enter.
![image](https://user-images.githubusercontent.com/35318508/34804718-7f1784c8-f650-11e7-867d-908dbdbac3d8.png)

If I try to change it, Update stays disabled.

![image](https://user-images.githubusercontent.com/35318508/34804750-a68e8182-f650-11e7-84ee-e752e569c647.png)

Say, I change something else. My name or my location, for example. I also change the display settings and press Update. It only changes my name or location. The display settings are back to 'always hide' when I reload the page.

I tried going into developer tools and dragging the display settings into the form, but this didn't solve the issue.

Otherwise great job, guys! I hope we can solve this. 😋

**Comment by pfunks** [comment] 2018-01-15 08:19
The NSFW setting is outside of the rest of the settings because to change the settings above it, a transaction is made. No transaction is made with the NSFW setting.

However there does seem to be a bug which I can reproduce in Firefox 57; changing the NSFW setting does not update the setting as it should. From what I recall, changing it did not need the Update or other button to be clicked. 

The design inconsistency on the same page with one group of settings needing the transaction signing Update button and other settings not needing it **is** an issue too. Some addition to the UI indicating the Steemit-specific cookie settings are changed would help. Or a new button saying "Update Steemit Settings" while the existing button would say "Update Account Profile"

**Comment by fildunsky** [comment] 2018-01-15 11:06
I have same issue in each and every browser. Language, NSFW and night mode settings are being reset to default each time I refresh a page.

**Comment by bnchdrff** [comment] 2018-01-15 13:25
fixed in 31fb893d3cec6aa50851f4875e123d0d0c4c89ed - thanks for your report!

**Closed by bnchdrff** 2018-01-15 13:25 UTC
