### ISSUE TITLE
Being logged out

### ISSUE THREAD

**Issue by TheDegenSloth** [steemit/condenser#1361] opened 2017-04-21 22:55 UTC
More times then not when i use my active key for anything i get logged out.

edit:
I think i found the problem, well when it happens.
On page load of new a refresh you're logged out instantly.

Currently using firefox on windows 10 it also happened on chrome as well.

**Comment by TheDegenSloth** [comment] 2017-04-23 01:06
I think i found the problem, well when it happens.
On page load of new a refresh you're logged out instantly.

**Comment by roadscape** [comment] 2017-07-21 19:32
Dupe of #1219

**Closed by roadscape** 2017-07-21 19:32 UTC
