### ISSUE TITLE
Show reputation of sender on wallet transfers

### ISSUE THREAD

**Issue by steevc** [steemit/condenser#1791] opened 2017-10-05 19:25 UTC
As we are getting more spam in the wallet and some attempted scams we need indications of issues with the sender. I think the reputation should be shown and if it's 25 or lower there should be a warning. If they haven't posted then they can't get flagged to reduce it.

**Comment by plink01001** [comment] 2017-11-16 02:13
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:13 UTC
Labels: enhancement-review
