### ISSUE TITLE
Image upload instructions should be available when editing a post

### ISSUE THREAD

**Issue by jredbeard** [steemit/condenser#1403] opened 2017-05-06 14:19 UTC
The 'select an image' link is only available on mobile when originally submitting a post, not when editing one.

**Comment by roadscape** [comment] 2017-07-21 19:40
This applies to desktop too.

**Comment by quochuy** [comment] 2019-05-10 11:37
Can't reproduce...
![Screen Shot 2019-05-10 at 9 36 13 pm](https://user-images.githubusercontent.com/310654/57524632-b95bb200-736b-11e9-82b7-3ae4bc150144.jpg)

**Comment by roadscape** [comment] 2019-05-13 15:45
Thanks @quochuy, closing this!

**Closed by roadscape** 2019-05-13 15:45 UTC
Labels: backlog, help-wanted, small+quick win
