### ISSUE TITLE
Bug : Comment sorting function

### ISSUE THREAD

**Issue by nhj7** [steemit/condenser#1924] opened 2017-11-04 03:32 UTC
I'm having trouble sorting comments.
Please take a look at the screenshot below.

![_2017_11_04_12_02_00_416](https://user-images.githubusercontent.com/32874559/32401820-26a7704e-c15a-11e7-8e55-ab018b6216d7.gif)

The first sort will work.
But after that, clicking does not work.
This bug is the same on my Android phone.

This is not serious, but I have used it often recently.

[Environment]
OS: window 10 Home 64bit
Browser: Chrome 62.0.3202.75 (64bit)

**Comment by plink01001** [comment] 2017-11-16 02:47
Duplicate of https://github.com/steemit/condenser/issues/1856

**Closed by plink01001** 2017-11-16 02:47 UTC
