### ISSUE TITLE
Comprehensive list of suggested UI/UX improvements to make to the Steemit.com website

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#195] opened 2016-08-28 05:45 UTC
I assembled a list of requested features for the Steemit.com website. It's a long wish-list, I suspect most won't get implemented (at least for a while), but hopefully this will help steer discussions about what features to work on.

There is a little bit of "post fluff" at the beginning and end (to interest the non-technical readers), but the list of features inside the post should be pretty clear.

https://steemit.com/ui/@timcliff/let-s-make-steemit-better-comprehensive-list-of-suggested-ui-ux-improvements-to-make-to-the-steemit-com-website

Updated with a new version:
https://steemit.com/steemit-ideas/@timcliff/the-steemit-wish-list-a-comprehensive-list-of-enhancement-requests-from-the-steemit-community-v1-1

Updated with a new version:
https://steemit.com/steemit-ideas/@timcliff/the-steemit-wish-list-a-comprehensive-list-of-enhancement-requests-from-the-steemit-community-v1-2

Latest version:
https://steemit.com/steemit-ideas/@timcliff/the-steemit-wish-list-avatars-notifications-multi-language-support-and-more-oh-my-v2-0

**Comment by plink01001** [comment] 2017-11-14 03:10
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:10 UTC
Labels: enhancement, enhancement-review, random, steemit-inc
