### ISSUE TITLE
Generating sitemap.xml for steemit

### ISSUE THREAD

**Issue by aaroncox** [steemit/condenser#1180] opened 2017-02-17 10:38 UTC
A service could be created that (daily) generates a series of sitemap.xml files (sharding the data to meet size restrictions). As for the method, whatever works best for the distributed architecture you guys have whipped up likely using a CDN and proxies from the frontend.

I spoke with @sneak about this briefly and decided to open an issue for tracking purposes. I realize this is a lower priority task, but I've seen the topic of SEO/sitemaps come up in chat a few times and it would be nice to have a place to refer people to for discussion/ideas.

**Comment by sneak** [comment] 2017-02-18 21:54
Why would we generate a static one and not generate it dynamically on request?

**Comment by aaroncox** [comment] 2017-02-18 22:17
I just assume a sitemap of that magnitude would end up being a very long and intense request. 

One of the other sites I run has a sitemap with around a million entries. If I were to generate it on request, it would take minutes of time processing. So I have a nightly process that outputs a static file onto the server to prevent generating it on request and unneeded monopolization of resources. 

It might be able to generate dynamically with some fancy footwork on the steemd rpc layer though.

**Comment by plink01001** [comment] 2017-11-14 03:49
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:49 UTC
Labels: enhancement-review, waiting-for-microservice
