### ISSUE TITLE
Feature: Auto-fill "title" and "body" fields when called with the proper query string

### ISSUE THREAD

**Issue by dragosroua** [steemit/condenser#1576] opened 2017-07-20 13:15 UTC
In submit.html the form using ReplyEditor could be auto-populated with _$title_ and _$body_ if accessed like this:

https://steemit.com/submit.html?title=encoded_title&body=encoded_body

This will allow the creation and dissemination of FacebookTwitter-like share buttons which will make posting easier, by decorating the URL of the button with a scheme like above.

I _think_ this is only a client / UI feature and it doesn't impact anti-spamming filters (throttling posting every 20 secs, etc) but a second opinion would be welcome.

If necessary, I can contribute buttons for creating a Steemit official "share on Steemit" or "Steem it" share button.

**Comment by plink01001** [comment] 2017-11-15 04:08
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:08 UTC
Labels: enhancement-review, feature-request
