### ISSUE TITLE
Link to go to start of comments at the top of posts.  [Feature]

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#1447] opened 2017-05-28 21:51 UTC
Sometimes posts are very long and we want to start reading the comments or access the controls that are after the post.

Something like that : 
![image](https://cloud.githubusercontent.com/assets/388716/26532424/4e55f6ec-43ce-11e7-924b-14fd92f0c181.png)

**Comment by plink01001** [comment] 2017-11-15 04:01
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:01 UTC
Labels: enhancement-review, feature-request
