### ISSUE TITLE
Miniatures in feed have weirdly cropped images

### ISSUE THREAD

**Issue by Gandalf-the-Grey** [steemit/condenser#1379] opened 2017-04-29 20:53 UTC
My image in [last post](https://steemit.com/witness-category/@gtg/vkn1k-gtg-witness-log) was supposed to show simple, black version of steem logo and in post itself looks great:
![gtg_steem](https://cloud.githubusercontent.com/assets/6341057/25558622/d626b936-2d2a-11e7-9764-009d2cb9b6cb.png)

Unfortunately its miniature in a feed is weirdly cropped and looks like this:
![bad_miniature](https://cloud.githubusercontent.com/assets/6341057/25558625/e4096a94-2d2a-11e7-89b1-2adac05426ad.png)

IMHO it would look much better if images for miniature purposes would be scaled, saving original aspect ratio

**Comment by roadscape** [comment] 2017-07-21 19:36
We can perform some experiments.

**Comment by roadscape** [comment] 2017-07-26 19:48
After/Before.. wdyt?
![image](https://user-images.githubusercontent.com/5168676/28640465-bfc2ef32-7219-11e7-9fc6-9efeb13be84c.png)

**Comment by Gandalf-the-Grey** [comment] 2017-07-26 20:03
I like it because it shows what's expected, i.e. miniature of the whole image.
In some cases it doesn't look as cool as before because of different aspect ratio, but at least user have a control over what exactly would be displayed.

BTW, what exact desired aspect ratio of such miniature?

**Comment by plink01001** [comment] 2017-11-15 03:58
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 03:58 UTC
Labels: enhancement-review, feedback-requested, UI
