### ISSUE TITLE
Enable embedding of mixcloud player into steemit posts

### ISSUE THREAD

**Issue by Ashaman-** [steemit/condenser#1751] opened 2017-09-23 21:18 UTC
Please enable the embedding of Mixcloud players/widgets. Soundcloud is a great, but they are really restrictive with regards to how much content you can upload on the free tier.

**Comment by plink01001** [comment] 2017-11-16 01:43
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 01:43 UTC
Labels: enhancement-review
