### ISSUE TITLE
bug-hunting for steemit: Voting is available in posts after 7 days.

### ISSUE THREAD

**Issue by landlove** [steemit/condenser#1937] opened 2017-11-07 07:09 UTC
Title : bug-hunting for steemit: Voting is available in posts after 7 days.

Problem :

Voting and unvoting are available for posts that are currently in the payout period.
Voting power will not be consumed
Any meaningless boat can go back and forth.
If it is intended, it should be modified to be impossible for Unvoting.

solution:

You must modify the posting period to not allow for Voting and Unvoting.

![4.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510034742/wymvlqi9ipmg1i1otvnh.png)

![11.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510034667/e46nwmsjkrdgg91pgi7f.png)

![113.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510034679/zbwpwp18zdjdi8arlnn7.png)

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@jungs/bug-hunting-for-steemit-voting-is-available-in-posts-after-7-days">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment] 2017-11-16 02:55
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:55 UTC
Labels: enhancement-review
