### ISSUE TITLE
Image proxy does not respect ratio with large portrait image

### ISSUE THREAD

**Issue by bonustrack** [steemit/condenser#1688] opened 2017-08-29 11:58 UTC
Image proxy does not respect ratio with large portrait image, example on this post:
https://steemit.com/colorchallenge/@permatek/colorchallenge-mondayred-french-mountain-flowers
The picture does not respect the ratio of the original picture. The proxy image crop the image. Here is the original image from post content: https://res.cloudinary.com/hpiynhbhq/image/upload/v1503924470/srsijqqicffbi1t3iztp.jpg

**Comment by plink01001** [comment] 2017-11-16 01:40
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 01:40 UTC
Labels: enhancement-review
