### ISSUE TITLE
Allow users to choose the image that shows as the post's thumbnail

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#359] opened 2016-09-29 05:33 UTC
Currently Steemit always uses the first image as a post's thumbnail in any post list. In order to give users better choice in formatting and image use/order, could the thumbnail be selectable in some way? Maybe a custom `<thumb></thumb>` tag around image code, for both HTML and markdown.

Additionally the thumbnail's aspect ratio and automatic cropping is problematic for certain images, particularly tall ones. Would it be possible to specify a thumbnail image that doesn't appear in the post at all?

**Comment by aaroncox** [comment] 2016-10-02 08:48
I believe the editor parses out all of the images and saves them in the `json_metadata` field. This means we should be able to add an image picker UI element below the post that let's the user choose from the images in the content visually or using a dropdown.

After the user chooses, there could also be a UI control that allows for a preview and possibly cropping. 

Would make for a pleasant experience 👍

**Comment by roadscape** [comment] 2016-12-09 18:21
I think a good way to accomplish this would be to have an optional `class="featured"` for `<img>` tags. When we are scanning the post for images prior to saving, we can make sure the first `featured` `img` (if any) has its URL saved first. It would be an easy complement to the next version of the editor.

**Comment by pfunks** [comment] 2016-12-10 12:26
Can it be made to be compatible with markdown image formatting as well?

**Comment by roadscape** [comment] 2016-12-12 17:43
@pfunks - you could theoretically use raw `<img>` tags in the markdown (with this class specified) and it would work just the same.

**Comment by sneak** [comment] 2016-12-12 17:44
>  It would be an easy complement to the next version of the editor.

😂

**Comment by roadscape** [comment] 2016-12-12 17:48
@sneak is convinced we can take over the world with just markdown.. ;)

**Comment by plink01001** [comment] 2017-11-14 03:20
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:20 UTC
Labels: enhancement-review, feature-request
