### ISSUE TITLE
Trending cycling too slowly

### ISSUE THREAD

**Issue by sens2** [steemit/condenser#1297] opened 2017-04-01 04:20 UTC
The momentum algorithm appears to be working well, however posts on the Trending page are cycling far too slowly. I have been seeing the same posts near the top for the last 48 hours now, many of which have stopped getting any significant activity 24 hours ago. I'd suggest changing the parameters, speed things up and targeting something fresh every 18 hours or so. 

Edit: At 1300 UTC, 4 out of the top 7 posts are 2 days old.

**Comment by plink01001** [comment] 2017-11-15 03:55
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 03:55 UTC
Labels: enhancement-review, feedback-requested
