### ISSUE TITLE
Can't receive SMS when signing up for steemit

### ISSUE THREAD

**Issue by nshadab** [steemit/condenser#2713] opened 2018-04-05 10:20 UTC
I'm not able to receive SMS while registering as a new member, with 3 different mobile numbers. Even I've passed the step of email confirmation, with the same email id with this Github account.

Trying for the last 8 days. Resent several times but no luck.

**Comment by gl2748** [comment] 2018-04-05 13:15
Hi @nshadab what country code are you trying to use when signing up? If India, I refer you to this issue:

https://github.com/steemit/faucet/issues/240
Specifically this comment:
https://github.com/steemit/faucet/issues/240#issuecomment-377063015

We are looking into improving the reliability of the SMS service we use. Do please let me know what country code you are using.

In the mean time i am closing this issue as a duplicate of:
https://github.com/steemit/faucet/issues/240

**Closed** 2018-04-05 13:15 UTC

**Comment by nshadab** [comment] 2018-04-05 17:15
i am using +91 as country code. I've checked with my mobile operator, and confirmed that i am not registered for DO NOT CALL Registry database, It means i am good to receive Twilio SMS.

**Comment by gl2748** [comment] 2018-04-05 18:11
hi @nshadab, quite right, 

This comment, posted above: https://github.com/steemit/faucet/issues/240#issuecomment-377063015 references this article:
https://support.twilio.com/hc/en-us/articles/223134167-Limitations-sending-SMS-messages-to-Indian-mobile-devices

There are other things contributing to you not receiving the sms.

**Comment by mjstroh** [comment] 2018-09-09 02:13
I am having the same issue from Australia today. Is there some restriction from this country?
