### ISSUE TITLE
Account verified, but took long to click on "finish verification" link.

### ISSUE THREAD

**Issue by Mandelsage** [steemit/condenser#2644] opened 2018-03-09 22:33 UTC
Hi there,

I registered with the account @wowbagger (email address: mandelsage.42@gmail.com ) and the verification e-mail came through, but I only saw it 7 days after it was sent. Now when I click on the link, it sends me to a steemit error page saying "Oops! Invalid token"
![image](https://user-images.githubusercontent.com/12225705/37233135-b952ef3a-23d0-11e8-951f-4cef00a990de.png)

Should I try registering it again with the same cell phone number?

**Comment by followbtcnews** [comment] 2018-03-09 22:39
Please goto https://steem.chat and use help channel there.

**Comment by Bazror** [comment] 2018-03-11 20:25
https://steem.chat no one help there.

**Comment by followbtcnews** [comment] 2018-03-11 20:33
Please goto #help channel in steem.chat and read the pinned messages. If your answer is not there,please send @drakos a DM there

**Comment by TimCliff** [comment] 2018-03-12 13:58
This is a duplicate of https://github.com/steemit/faucet/issues/246 and can be closed.

**Closed** 2019-04-23 15:50 UTC
