### ISSUE TITLE
Add ability to bookmark/favorite posts 

### ISSUE THREAD

**Issue by bitcoiners** [steemit/condenser#1674] opened 2017-08-23 00:53 UTC
Many good posts get lost and are not easy to find after a while.
We would all benefit from ability to bookmark a post or mark it as favorite and we can have another tab in user profile to see favorites/bookmarks.

**Comment by JoshTristram** [comment] 2017-08-29 10:55
They have it on busy.org

**Comment by nurazhar** [comment] 2017-10-07 09:09
@JoshTristram so you want us to use busy.org? also there's no dislike button

hate clickbaits

**Comment by plink01001** [comment] 2017-11-15 04:16
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:16 UTC
Labels: enhancement-review
