### ISSUE TITLE
Pre-Fill Transfer Form from URL

### ISSUE THREAD

**Issue by Netherdrake** [steemit/condenser#668] opened 2016-11-18 15:22 UTC
## Why
At SteemSports we are implementing a form to take users private ACTIVE keys to make bets.
The key is used to sign in the browser, and then garbage collected. It is never sent to server, or saved in localStorage, etc.

However we also have chat, and images embedded from blockchain posts, and no full-time security experts. So I think that eventually someone will find a way to steal keys while they are inputted.

Therefore, it would be better to do payments on steemit.com

## Solution
I propose a special secure page, that can take form values from URL, and pre-fills the payment form. Then, the only thing user needs to do is sign with their private key or password.

## Example
https://steemit.com/securetransfer/@furion/100/SBD/memo+here

This will pre-fill the payment form like this:
![](http://i.imgur.com/iQurGIr.png)

## What this enables us to do
This allows us, and anyone else to simply generate payment links, and offer convenient payment options while reducing the risk of losing people's keys.

**Comment by jcalfee** [comment] 2016-11-18 16:23
We have been discussing wallet signing and single sign on .. I think this is an excellent place to start.

What do you think about this format?

https://steemit.com/transaction#transfer&to=furion&amount=100+SBD&memo=memo+here

* The hashtag has a side-effect that the information is not sent to the server on the initial page load.  
* The string after the hashtag should be parsable by standard url query libraries.
* Any word without an equal after it (`transfer`) indicates the start of a new operation (later a transaction preview could support multiple operations).
* The labeled fields correspond to the fields found in the standard STEEM transaction operations and also help the reader understand the URL.
* Labels like `to=` and `from=` being after the hashtag should also allow for duplicate field names should those be needed in another operation in the same url query.

**Comment by roadscape** [comment] 2016-11-18 16:40
From 668:

> I would love to be able to prefill a transfer window with 'TO, AMOUNT, MEMO', maybe via URL params?
> 
> This would fix typos? and make it easier to use the money transfer functionalities for end-users. 
> Optionally a 'callback url' would be even greater after a succesfull payment to send a user to the 'paymentsuccesfull.html' page
> 
> Additionally it might be smart to turn these user based 'self' URI's to: 
> - steemit.com/my/transfers
> - steemit.com/my/posts
> - steemit.com/my/blog
> 
> etc.
> 
> Kind regards Roelandp
>

**Comment by jcalfee** [comment] 2016-11-18 16:43
From #64: 
> Optionally a 'callback url' would be even greater after a succesfull payment to send a user to the 'paymentsuccesfull.html' page

A browser-based javascript callback to a 3rd party CORS server would be the best thing for us so we don't have to worry about server security and abuse and bascially the recipient must consent to receive the CORS request.  In other words, the browser updates the 3rd party directly on the status of the transaction.  There are probably two events: broadcasted (out the door) and then seconds later accepted (was added to a block).

**Comment by Netherdrake** [comment] 2016-11-18 17:07
Just a minor UI suggestion.

If one of the parameters is missing (ie. the link doesn't contain `to=furion` part), then highlight the missing field in the form, so users quickly see what needs their attention.

**Comment by adcpm** [comment] 2016-11-18 17:14
We have this page with Steem Connect:
https://dev.steemconnect.com/transfer/@furion/150/SBD/Hello
![image](https://cloud.githubusercontent.com/assets/16245250/20439200/d67d1cda-adba-11e6-8df4-489fbf53892c.png)
But i agree that this format is better: to=furion&amount=100+SBD&memo=memo+here

It would be nice to have an embed version that we can add with an iframe on any app.

**Comment by jcalfee** [comment] 2016-11-18 17:25
Glad you brought up iframes.  Steemit.com has to be careful of iframes because this will prompt for an active key or password.  At the very least the user must see the address Https url and certificate lock icon.  A pre-saved saved voting or posting key could perhaps work in a iframe (does not apply to this ticket).

**Comment by adcpm** [comment] 2016-11-18 17:52
Right! User need to be able to verify the source of the frame. Steemit could use this format for transfer:
![](https://our.umbraco.org/media/wiki/8577/634128328700638000_facebookConnect02.jpg)

**Comment by Netherdrake** [comment] 2016-11-18 17:54
Ok, another minor idea: 
Allow for 'callback url' in parameters, so if specified, user will be redirected back to that page once transfer is signed/rejected.

**Comment by jcalfee** [comment] 2016-11-18 18:13
I think we are going to need to block the frame and iframe as follows until we have good secure workarounds:

* https://en.wikipedia.org/wiki/Framekiller (thanks roadscape)
* http://stackoverflow.com/questions/19843085/how-to-block-website-from-loading-in-iframe

**Comment by Netherdrake** [comment] 2016-11-21 13:09
Is there an ETA on when this feature will be implemented?

**Comment by jcalfee** [comment] 2016-11-21 20:35
I have no ability anymore to add features.  There is nothing I can do to help you.

**Comment by Netherdrake** [comment] 2016-11-21 21:03
Is anyone working on this?

**Comment by jcalfee** [comment] 2016-11-21 22:25
@sneak

**Comment by jcalfee** [comment] 2016-11-21 22:26
@sneak is anyone working on this?

**Comment by sneak** [comment] 2016-11-24 13:32
Not yet. For us to proceed with this would require some authoritative statements stemming from research into whether or not this is resistant to clickjacking attacks.

**Comment by sneak** [comment] 2016-11-24 13:35
> However we also have chat, and images embedded from blockchain posts, and no full-time security experts. So I think that eventually someone will find a way to steal keys while they are inputted.

Also: this is why you should *not do this*. Don't handle users' keys. Please.  We will be educating users in the future about providing their keys to third-parties (that is: telling them *not to*).

**Comment by plink01001** [comment] 2017-11-14 03:28
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:28 UTC
Labels: enhancement-review, feature-request, priority/medium, UI
