### ISSUE TITLE
Unable to confirm phone number

### ISSUE THREAD

**Issue by Ansa552** [steemit/condenser#2982] opened 2018-08-16 00:41 UTC
I selected phone area +58, then writed my phone number (starting with 0) and clicked on continue, but nothing happened

**Comment by TimCliff** [comment] 2018-08-16 16:35
This is a duplicate of https://github.com/steemit/faucet/issues/359. You can add any details to that issue if you have any new relevant information.

**Closed** 2019-04-23 19:59 UTC
