### ISSUE TITLE
Tip Button

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#401] opened 2016-10-04 00:40 UTC
Add a tip button to comments and posts

**Comment by faddat** [comment] 2016-10-06 15:33
Profile pages, too.  This could be useful in a number of ways, for example, anyone with a steemit account would suddenly also have a publicly accessible place where people could click on their profile, and send them money (as opposed to the current situation where one must go to the wallet and manually setup a transfer to another user.)

**Comment by sneak** [comment] 2016-10-08 04:25
I think this is an awesome suggestion.

**Comment by sneak** [comment] 2016-10-08 04:26
![](https://github.trello.services/images/mini-trello-icon.png) [tipping button on posts/profile pages](https://trello.com/c/0BKV5UIF/61-tipping-button-on-posts-profile-pages)

**Comment by theoreticalbts** [comment] 2016-10-13 21:35
@mvandeberg and I were talking about this.  The UI element for tipping a post should be hidden or greyed out unless you have a balance of at least $0.10 worth of SBD / STEEM and have already upvoted the post.  We don't want to clutter the UI with an element that isn't relevant to the user's situation.

**Comment by theoreticalbts** [comment] 2016-10-13 21:39
One of the core philosophical principles of Steem is we can reduce users' cognitive load by not bombarding them with decisions to spend tokens at every turn.  In other words, a key design heuristic of Steem is that Microtransactions Are Bad.

Tipping is a microtransaction.  Before we implement a tipping UI, we need to figure out why (or whether) tipping is exempt from the Microtransactions Are Bad design heuristic.

**Comment by sneak** [comment] 2016-10-13 22:54
Tipping doesn't have to be a microtransaction; it is reasonable to expect $5 tips here and there.

As for UI - greyed out is good, hidden and then magically appearing is bad because it (usually) means that the UI elements get moved around unpredictably (from the user's perspective).  It's best to keep whatever UI chrome in a fairly consistent layout, even if it's disabled in the user's current mode.

**Comment by faddat** [comment] 2016-10-13 23:20
Just to be clear,

I don't think it's really just tipping.   I wonder if we could find another
word for it.  I'm thinking more something that would emphasize the "pay N
person $Y" aspect of this.

Who knows?  It could be that such an interface was all that was needed to
get people to realize the greatness of cryptocurrency blockchains (and thus
use them).  Could be "send SD to @*user" on the button or similar.  This
also gives people a reason to buy into the ecosystem:  Global transfers of
value are still hard as hell.

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by thebitcoiner** [comment] 2016-10-13 23:24
Something like Send, Give, or Gift would do well.

**Comment by faddat** [comment] 2016-10-13 23:31
Verbify STEEM meaning "send cash to"?

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +84 167 789 6421

**Comment by TimCliff** [comment] 2016-10-14 16:22
It is a little bit different than what I originally suggested, but if we are looking to add more of a "send money" feature, it could be part of the options that show up when you click on a username (along with profile, follow, and mute).

**Comment by jcalfee** [comment] 2016-10-14 16:59
It would be really good if we had a tips plugin that totaled these up per post.  Otherwise tips will mostly be unnoticed.

**Comment by TimCliff** [comment] 2016-12-11 02:16
Related issue: https://github.com/steemit/steem/issues/690

**Comment by TimCliff** [comment] 2017-03-12 19:56
Busy.org just submitted a PR along these lines:
https://github.com/adcpm/busy/pull/407

**Comment by plink01001** [comment] 2017-11-14 03:21
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:21 UTC
Labels: enhancement-review, feature-request
