### ISSUE TITLE
RSS subscription

### ISSUE THREAD

**Issue by miohtama** [steemit/condenser#34] opened 2016-07-03 18:59 UTC
Good work with great concept!

Currently it seems it is not possible to subscribe to RSS feeds to read the latest steem updates. Is this correct?

**Comment by jcalfee** [comment] 2016-07-03 19:10
Correct, no RSS feed yet...

**Comment by samupaha** [comment] 2017-03-14 10:16
Any chances getting RSS implemented in the near future?

I read lots of blogs and pretty much all of them I'm following with RSS reader. RSS feed is great way to get notified when a new post is published without having to visit the site. For me it's also the preferred (in practice: the only) way to read blogs with mobile device. The user experience is great because I need only one app that can show me quickly everything I want to read.

I'd love to have several different RSS feeds:
- Posts by author
- Posts + comments by author (some authors are so interesting that I want to read everything they write on Steemit)
- All comments for a post (when somebody writes an interesting post, I want to be able to follow the discussion)
- All comments for posts by author (mostly for an author to follow easily all the comments that he gets to his own posts)

Pretty much all blogging and news sites offer RSS feeds because it is a great way to get long time readers. It's time to get this on Steemit, too.

**Comment by plink01001** [comment] 2017-11-14 03:00
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:00 UTC
Labels: enhancement-review, feature-request, nicetohave, waiting-for-microservice
