### ISSUE TITLE
Fixing schema.org meta data for article

### ISSUE THREAD

**Issue by DennisAlund** [steemit/condenser#2133] opened 2017-12-09 21:00 UTC
# Issue
Blog posts are using the wrong [Schema.org](http://schema.org/) schema type. 

 * Reported in github issue [#2118](https://github.com/steemit/condenser/issues/2118) 
 * Proposed solution in github pull request [#2119](https://github.com/steemit/condenser/pull/2119)

# Before
![Broken meta data](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512705485/dwuuiitnddu29y2ehjgg.png)

# After 
![No errors](https://res.cloudinary.com/hpiynhbhq/image/upload/v1512705462/a1euupoyufbvynbabahk.png)

<br /><hr/><em>Posted on <a href="https://utopian.io/utopian-io/@dennisalund/fixing-schema-org-meta-data-for-article">Utopian.io -  Rewarding Open Source Contributors</a></em><hr/>

**Comment by bnchdrff** [comment] 2017-12-10 03:32
this is a dupe of #2118

**Closed by bnchdrff** 2017-12-10 03:32 UTC
