### ISSUE TITLE
Add ability to resteem old posts

### ISSUE THREAD

**Issue by bitcoiners** [steemit/condenser#1675] opened 2017-08-23 00:56 UTC
I am often unable to share a good post with readers of my blog because it is apparently considered too old by condenser. Ability to resteem is missing on posts even a few weeks old. This is not good.

**Comment by Siko91** [comment] 2017-08-24 11:05
Currently, when resteeming 2 posts that were made before 1 hour the first and 2 hours the second, the newer one will always appear before the old one, completely ignoring the order they were resteemed in.

Even if you resteem an old post, it will appear so far behind in your feed, that nobody will see it anyway.
It will probably be the same in your follower's feeds.

Unless the sorting algorithm itself is changed, your request wouldn't make sense to implement.

**I believe the sorting should be improved.**
If not in the general feeds - at least in the blog of the user who resteems.

**Comment by roadscape** [comment] 2017-08-24 14:41
Resteems should be showing in follower feeds in the order they were resteemed, unless it's already in a particular feed. I don't recall seeing any cases where a newly resteemed post is not pushed to the top of user's feeds.

**Comment by Siko91** [comment] 2017-08-25 11:26
My mistake.

**Comment by plink01001** [comment] 2017-11-15 04:17
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:17 UTC
Labels: enhancement-review
