### ISSUE TITLE
Resteems tab on the user profile page

### ISSUE THREAD

**Issue by nkgokul** [steemit/condenser#1655] opened 2017-08-12 10:16 UTC
Based on the following posts [Can Resteems save Steemit](https://steemit.com/steemit/@gokulnk/can-resteems-save-steemit) and [Request to Add Shares Tab for Resteems!](https://steemit.com/steemit/@jerrybanfield/request-to-add-shares-tab-for-resteems) I think adding a Resteems would be a great feature addition.

**Comment by TimCliff** [comment] 2017-08-12 18:40
It is a good suggestion, but the GitHub repository is not the place to submit enhancement requests. Please read the guidelines for contributing before opening issues. @sneak to close.

**Comment by plink01001** [comment] 2017-11-15 04:15
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 04:15 UTC
Labels: enhancement-review
