### ISSUE TITLE
Transaction broadcast error. Network request failed. 502.

### ISSUE THREAD

**Issue by etartakovsky** [steemit/condenser#1934] opened 2017-11-06 17:36 UTC
I was trying to submit an article and got the following error after hitting `Post`:
UI: http://take.ms/1ue32
Console: http://take.ms/q7Z2H

**Comment by bnchdrff** [comment] 2017-11-07 13:45
dupe of https://github.com/steemit/condenser/issues/1871 -- we are working on it!

**Closed by bnchdrff** 2017-11-07 13:45 UTC
