### ISSUE TITLE
header element blocks article title

### ISSUE THREAD

**Issue by littlemiddlebiddle** [steemit/condenser#3385] opened 2019-05-29 17:50 UTC
**Specifications:
* FF 60.6.1 ESR
* Windows 7
* 1920px window.innerWidth;
* 960px window.innerHeight

**Steps to reproduce the problem:**

1. Navigate to https://steemit.com/steamit/@noisy/steem-bug-bounty-program-how-to-reports-bugs-and-new-ideas in browser and wait for the ad to load

**Actual behavior:**
* Ad blocks part of title
![image](https://user-images.githubusercontent.com/14179790/57563850-10b05100-7371-11e9-905b-b76b84df4ba5.png)

**Expected behavior:**
* Ad does not block title or page content and is as non-invasive as possible

**Comment by quochuy** [comment] 2019-05-29 22:27
This is a duplicate of https://github.com/steemit/condenser/issues/3281

**Comment by roadscape** [comment] 2019-06-10 15:20
Blocked by https://github.com/steemit/condenser/pull/3390

**Comment by roadscape** [comment] 2019-06-20 16:46
https://github.com/steemit/condenser/pull/3404 contains more mitigations

**Comment by JonathanPorta** [comment] 2019-06-20 16:47
To get ads to show up locally set these environment variables:
```
GPT_ENABLED=true
GOOGLE_AD_CLIENT=ca-pub-9368037717385698
GOOGLE_AD_ENABLED=true 
```

**Comment by quochuy** [comment] 2019-06-26 05:40
@roadscape I guess this one is already solved

**Comment by roadscape** [comment] 2019-06-26 15:40
We've experienced some rare but lingering issues, thinking it may be due to CSP violations not being handled.

**Comment by quochuy** [comment] 2019-07-22 08:04
@roadscape why not move the advert banner outside of the header into the top of the article, above the title. So that the header height is never modified.

**Closed** 2020-01-07 18:16 UTC
Labels: bug, help-wanted
