### ISSUE TITLE
Flag popup behind elements on beta site

### ISSUE THREAD

**Issue by themarkymark-steem** [steemit/condenser#3687] opened 2020-01-23 21:15 UTC
on the beta site when flagging (potentially when upvoting) the panel falls behind the post elements from time to time.  This only appears to happen on the beta site.

Gif of it in action
https://i.imgur.com/HTdvG2H.gifv

**Comment by gl2748** [comment] 2020-01-31 14:23
@themarkymark-steem what browser are you using?

**Comment by themarkymark-steem** [comment] 2020-02-01 01:53
Brave

**Comment by gl2748** [comment] 2020-02-03 14:52
I'm not able to reproduce on Brave.
- In dark mode.
- Click downvote on a post.
- Submit vote on the drowdown that appears.
- Click downvote on some other post.
- Scroll so that the dropdown is not in view.
- Scroll back up.
- Expectation per the issue is that the dropdown will not appear behind the list of posts. However I have not been able to reproduce this...

<img width="834" alt="Screen Shot 2020-02-03 at 9 49 50 AM" src="https://user-images.githubusercontent.com/3374538/73662881-92b47880-466a-11ea-9dbe-f35d4e07a297.png">

**Comment by roadscape** [comment] 2020-02-05 18:36
Please reopen if there are more details on how to reproduce.

**Comment by themarkymark-steem** [comment] 2020-02-07 04:18
I have been able to reproduce it 100% of the time in both Brave and Chrome doing this.

https://i.imgur.com/8NlRDqV.gifv

The key thing seems to be moving the mouse to the left before actually submitting the flag.

**Comment by gl2748** [comment] 2020-02-07 15:50
Thanks @themarkymark-steem

**Comment by gl2748** [comment] 2020-02-11 14:59
Still not able to reproduce in dev environment.

![Kapture 2020-02-11 at 9 49 11](https://user-images.githubusercontent.com/3374538/74248174-2d3d3900-4cb5-11ea-8d5c-5b6b14f90b12.gif)

**Comment by jredbeard** [comment] 2020-02-12 19:12
@themarkymark-steem any chance you are using steemplus or any other chrome extensions?

Also unable to reproduce on my end...

**Comment by roadscape** [comment] 2020-02-12 19:51
It looks like this specifically affects postlist items which are grayed out.

I scrolled down a bit on https://beta.steemit.com/@themarkymark/replies, and found a grayed out post (the middle one here):
![image](https://user-images.githubusercontent.com/5168676/74371585-ac5a6c00-4d9e-11ea-976a-66ad8977f0c8.png)

This item consistently reproduces the behavior.

**Comment by themarkymark-steem** [comment] 2020-02-13 19:57
I am typically seeing it when I am in the **muted** list.  That might be part of the problem.
I do not run SteemPlus, I can try safe mode if **muted** doesn't reproduce it.

**Comment by roadscape** [comment] 2020-02-18 16:29
The issue is in:

```
.downvoted {
    opacity: 0.5;
    transition: 0.2s all ease-in-out;
    [...]
}

.downvoted:hover {
    opacity: 1;
    filter: none;
    -webkit-filter: none;
}
```

`.downvoted` is applied to the PostSummary container, which means the dropdown inherits `opacity: 0.5`, and `z-index` cannot bring it to top, seemingly because:

> [Since an element with opacity less than 1 is composited from a single offscreen image, content outside of it cannot be layered in z-order between pieces of content inside of it.](https://www.w3.org/TR/css-color-3/#transparency)

What we need is a CSS refactor to ensure `downvoted` is used consistently and it targets specific elements. (Currently, it's used for both PostSummary and Comment.) Since this bug does not critically impact UX, and condenser is in need of general CSS cleanup, I'm going to close this particular issue for now.

**Closed by roadscape** 2020-02-18 16:29 UTC
Labels: bug, communities
