### ISSUE TITLE
view page for specific comment does not display comment's children

### ISSUE THREAD

**Issue by sneak** [steemit/condenser#814] opened 2016-12-08 07:37 UTC

**Comment by roadscape** [comment] 2016-12-08 15:13
Might be dupe of #440

**Comment by mcifani** [comment] 2016-12-21 18:11
@sneak comment reply tree should be showing on a specific comment/permalink. Could you describe a bit further you thoughts for this. Thanks

**Comment by mcifani** [comment] 2016-12-21 18:27
![](https://github.trello.services/images/mini-trello-icon.png) [view page for specific comment does not display comment's children #814](https://trello.com/c/g9HxXWA8/161-view-page-for-specific-comment-does-not-display-comment-s-children-814)

**Comment by plink01001** [comment] 2017-11-09 02:54
Has this been addressed / can this be closed?

**Comment by plink01001** [comment] 2017-11-14 03:32
This seems resolved. Closing.

**Closed by plink01001** 2017-11-14 03:32 UTC
Labels: enhancement, priority/medium, small+quick win, UI
