### ISSUE TITLE
Steem reputation score not accurate

### ISSUE THREAD

**Issue by postandbeam82** [steemit/condenser#2307] opened 2018-01-09 13:40 UTC
My Steem reputation score is different in my blog (47) than when I'm in my wallet (25).  I'm worried this is affecting my influence or payouts.

User name is postandbeam82

**Comment by bnchdrff** [comment] 2018-01-09 13:42
Duplicate of #2306

Hi postandbeam82, thanks for the bug report -- this is a known issue and a fix is in the works!

**Closed by bnchdrff** 2018-01-09 13:42 UTC

**Comment by postandbeam82** [comment] 2018-01-09 13:50
Awesome thanks!
