### ISSUE TITLE
Implement Basic Blogging Interface of Blogger

### ISSUE THREAD

**Issue by bytemaster** [steemit/condenser#911] opened 2016-12-26 16:57 UTC
On the right side of blog posts we should have:

1. Popular 
2. Blog Posts sorted by Date 
3. Tags used by this blogger 

![image](https://cloud.githubusercontent.com/assets/347290/21484546/4bb0636c-cb62-11e6-8728-217ab0d39bc5.png)

![image](https://cloud.githubusercontent.com/assets/347290/21484552/5f0b0c82-cb62-11e6-98dc-30cc557dedc1.png)

**Comment by plink01001** [comment] 2017-11-14 03:36
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:36 UTC
Labels: enhancement, enhancement-review, feature-request, priority/low, waiting-for-microservice
