### ISSUE TITLE
Suggestion - Sort in Real Time

### ISSUE THREAD

**Issue by hdmed** [steemit/condenser#2026] opened 2017-11-18 09:19 UTC
# Suggestion - Sort in Real Time
![Moroccan Community   teammorocco  — Steemit.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510926296/bolj3qzfdd5p02ubsnaa.png)

We like to see in our blog, a drop-down list that allows to sort posts, by different criteria like:
- By date
- By number of views
- By number of votes
- By rewards value
- By number of comments
- And of course from A to Z and from Z to A.
## Like that of YouTube.
![37  TeamMorocco   YouTube   YouTube.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1510926557/xkuu3fmht4azobfq6esv.png)

**Comment by plink01001** [comment] 2017-11-21 03:52
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-21 03:52 UTC
Labels: enhancement-review
