### ISSUE TITLE
Can not register because sms verification is not working.

### ISSUE THREAD

**Issue by Mrkrx** [steemit/condenser#1970] opened 2017-11-12 00:50 UTC
Tried it with 2 different phone numbers and still nothing.
I am from Latvia and i have latvian number (+371) so that might be an issue.

**Comment by plink01001** [comment] 2017-11-16 03:09
Duplicate of https://github.com/steemit/condenser/issues/1426
If you are having issues with account signup, ask for help in the steemit.chat help channel.

**Closed by plink01001** 2017-11-16 03:09 UTC
