### ISSUE TITLE
idea : url link needs to be added.

### ISSUE THREAD

**Issue by nhj7** [steemit/condenser#1938] opened 2017-11-07 07:59 UTC
There are many third party sites related to 'steemit'. We use that many sites. Typically, there is 'steemd.com'. There are many such sites.

steemus.com
steemnow.com
steemwhale.com
steemkr.com
http://tool.steem.world/Post/BestFriendPosts
http://soboru.co.uk/steemme/
https://nhj1002.github.io/
...etc... so many many.

I think it should be easy to access the site for these features, so you need to have the ability to bookmark these sites in steemit.com.

If I do, I will add it here.

Currently at steemit.com
![asis.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509934995/x8s85ut8l1k3yrkp2ulm.png)

After adding steemit.com...
![add links.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509935114/rugvslgm5nfcnclnvbjj.png)

Click on 'Link' to create a pop-up below to add a link.
![add link popup.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509935238/uauqyvwzm1fpguapcfkr.png)

It is the screen which added 'steemd.com'.

![result pic.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509935288/gqodqe0bamvtpfnebwcx.png)

Click '-' to be able to delete it.
![image.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509935376/lqkewcksjg3bohhhfhro.png)

I think you can save it to json_meta in your 'steemit' account information, or use client browser's local storage.

I hope my ideas will be reflected. And thanks for reading.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@nhj12311/idea-url-link-needs-to-be-added">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment] 2017-11-16 02:56
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:56 UTC
Labels: enhancement-review
