### ISSUE TITLE
Advanced search for filtering, fulltext

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#125] opened 2016-08-12 02:52 UTC
I would love to see an advanced search feature added to Steemit! It would be a great way for content curators to dig for undiscovered content.

https://steemit.com/ui/@timcliff/steemit-feature-request-advanced-search

**Comment by faddat** [comment] 2016-08-20 14:17
I just wanted to pipe in here that I'd be glad to run an elasticsearch or similar, and think that my infrastructure can handle the load.  Only one way to find out, right?

**Comment by faddat** [comment] 2016-09-01 12:02
So i did put up an elasticssearch cluster, however i am not too sure how to connect that to all of this.  Do y'all want some help with all of that?

(All of that == orchestrating the spaghetti to achieve a congruent functional whole). If so just let me know how specifically i can help.

**Comment by roadscape** [comment] 2016-09-22 21:20
Related user concept: https://steemit.com/steemit-ideas/@t3ran13/idea-for-steemit-com-little-functionality-improvement-add-tags-to-person-blog-and-feed

**Comment by faddat** [comment] 2016-09-24 16:58
That's a cool related user idea...

**Comment by roadscape** [comment] 2016-11-03 20:20
![](https://github.trello.services/images/mini-trello-icon.png) [Search](https://trello.com/c/m59xvgXV/109-search)

**Comment by plink01001** [comment] 2017-11-14 03:08
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:08 UTC
Labels: enhancement, enhancement-review, feature-request, major-feature, priority/low

**Comment by joticajulian** [comment] 2018-03-26 15:44
I have created a tool to filter the searches. It is called Custom Feed.

https://steemit.com/utopian-io/@jga/introducing-custom-feed-filter-the-authors-and-posts-that-you-want-to-read

In the future it would be interesting to include these options in the condenser
