### ISSUE TITLE
Factor promotion SBD into a post's trending ranking

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1072] opened 2017-01-28 10:45 UTC
Post promotion should provide an extra ranking boost not only in the promotion tab but also in any trending ranking (per-tag and overall) on steemit.com. I don't have the numbers but I would guess there are more visitors to the overall trending page than the promoted page. Adding the promotion SBD amount to the post's potential payout for ranking purposes would give a lot of extra value to promoting posts.

For example, [Joseph's post here](https://steemit.com/zdash/@joseph/an-update-on-zdash-a-zcash-alternative) has been promoted with 21.00 SBD.

![image](https://cloud.githubusercontent.com/assets/22420130/22396011/991c06ea-e513-11e6-8c40-f5088b178a34.png)

But it does not rank above posts with more potential payouts that are less than the total promotion SBD+potential payout of his post, in specific tag trending lists or in the main trending list.

![image](https://cloud.githubusercontent.com/assets/22420130/22395982/0ade2f70-e513-11e6-8b62-dcfcc3fac47c.png)

![image](https://cloud.githubusercontent.com/assets/22420130/22396032/28aec0d6-e514-11e6-98c6-a04bca07c444.png)

**Comment by adcpm** [comment] 2017-01-31 19:32
I agree on this but I think it should be handled by the blockchain, i created a similar issue few months ago https://github.com/steemit/steem/issues/497

**Comment by iamsmooth** [comment] 2017-01-31 21:02
i dont like the idea 

i think some promoted posts should be displayed on the trending page, but separately identified the way most web sites with paid placement do

Could be 2-3 top-ranked promoted posts shown at the top, or interspersed, but in either case with some sort of "Promoted" tag or box label.

**Comment by liondani** [comment] 2017-01-31 21:23
when you type something in google you see first the ads 
it could be only top 1-3 promoted  post on trending page not more
so there will be a competition wich one gets in top 3 promoted!
And i would like when someone burns SBD for promotion that the post get a time boost and ends later! I would burn a bunch of SBD for some promoted post before they expire 
(get paid)

**Comment by clayop** [comment] 2017-01-31 21:25
I think the idea is good but agree with @adcpm. It needs to be blockchain-level feature.

**Comment by roadscape** [comment] 2017-01-31 21:31
It will most likely not be a blockchain feature (UI concerns generally don't belong in the node). One idea is to have a promoted post at the top of every "page" (i.e. every 20 posts), ranked by promotion cost.

```
promoted #1
posts 1-20
promoted #2
posts 21-40
promoted #3
posts 41-60
```

**Comment by liondani** [comment] 2017-01-31 21:33
I like it and it could be easily every 10 posts

**Comment by aaroncox** [comment] 2017-02-01 01:16
Chalk my vote up for this being a non-blockchain feature. 

Any other project that uses the steemd API shouldn't be subject to this content being interjected into a feed of content. It would be nice if the website owners using the API choose to include it, but shouldn't be required/forced on the blockchain API level.

I do see the value in the content being intermixed in feeds though, especially in an interface like steemit.com, as long as it's called out.

**Comment by TimCliff** [comment] 2017-02-01 01:33
I like the idea of introducing promoted posts within 'regular' content. 

Another variation on it would be to have the selected posts be a weighted random pick. There would still be incentive for promoting for higher amounts (more frequent picks) but it would not limit the exposure to just the people that could afford the top slots.

**Comment by plink01001** [comment] 2017-11-14 03:40
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:40 UTC
Labels: enhancement-review, feedback-requested, UI, waiting-for-microservice
