### ISSUE TITLE
Can we get vid.me embeds?

### ISSUE THREAD

**Issue by FreeBornAngel** [steemit/condenser#960] opened 2017-01-07 21:11 UTC
I want to post a video, but I don't want to use youtube, anymore.

<iframe src="https://vid.me/e/5As?stats=1" width="640" height="360" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>

Even better if the html recognized the link and sought a fingernail?
https://vid.me/5As

**Comment by FreeBornAngel** [comment] 2017-01-08 23:39
https://steemit.com/vidme/@titusfrost/youtubers-switching-to-vid-me-centralized-control-or-decentralized-anarchy-the-choice/

**Comment by plink01001** [comment] 2017-11-14 03:36
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:36 UTC
Labels: enhancement-review, feature-request
