### ISSUE TITLE
The page doesn't focus on the comment when browsing to a comment link

### ISSUE THREAD

**Issue by Jolly-Pirate** [steemit/condenser#2011] opened 2017-11-16 22:28 UTC
When browsing to a comment link, for example https://steemit.com/roadmap2018/@steemitblog/steemit-roadmap-2018-community-input-requested#@drakos/re-steemitblog-steemit-roadmap-2018-community-input-requested-20171116t210955021z, the page doesn't focus on the comment but stays at the top. 

In the previous condenser version (from october), this works fine. For example https://yehey.org/roadmap2018/@steemitblog/steemit-roadmap-2018-community-input-requested#@drakos/re-steemitblog-steemit-roadmap-2018-community-input-requested-20171116t210955021z

**Comment by TimCliff** [comment] 2017-11-17 00:34
Duplicate of https://github.com/steemit/condenser/issues/1946. A PR has already been created/merged.

**Comment by plink01001** [comment] 2017-11-17 03:19
Closing duplicate.

**Closed by plink01001** 2017-11-17 03:19 UTC
