### ISSUE TITLE
Show the complete list of witnesses on steemit.com/~witnesses

### ISSUE THREAD

**Issue by l0k1verloren** [steemit/condenser#1296] opened 2017-03-31 20:50 UTC
There is currently something like 69 witnesses, so about 19 of the witnesses are difficult to vote for for new users who don't understand the key system. 

There is no logical reason why the full list of up to 100 witnesses cannot be shown on this page, and it conveys an attitude towards the backup witnesses that especially new users voting for them does not matter.

It should not be relevant that indeed their votes do not have very much influence. This goes against the principle of democracy that the rest of the platform presents; It excludes them and the backup witnesses from participation, and this problem is worse when the witness name is easy to mistype.

**Comment by TimCliff** [comment] 2017-04-17 14:25
Currently a majority of the witnesses below 50 are not active. As a backup witnesses who was below 50 for a long time, I never had an issue with it. It was something to aim for, and an accomplishment once I got there. Regardless though, this issue tracker is not the place for enhancement suggestions. @sneak to close.

**Comment by noisy** [comment] 2018-05-29 22:06
I think, this issue should be revisited. I waited a long time, so I could say that from a perspective of person which is already in top50.

It is in best interest of all top50 witnesses, to not change that (duh!), but this is in best interest of whole Steem blockchain, to make witnessing more competitive.

Actually current situation is not only far from being fair, it is really causing anomaly like this: 

![since top50](https://user-images.githubusercontent.com/201263/40687342-9cc224a8-639a-11e8-9d4c-2a00eef100a5.png)

People in top50 list gets a lot votes just because they are in top50.

If that would not be enough, having only 50 people in this list, really creates wrong impression of blockchain as a decentralized network. People which are in crypto for many years, which suddenly joined Steem, they asked me: _why Steem has only 50 nodes_.

Another problem with top50 list is... that it is actually not intuitive to vote for someone from outside of top50.

take a look on this:

----
![selection_520](https://user-images.githubusercontent.com/201263/40687774-04980b14-639c-11e8-9893-4a2581ef6749.png)
----
![selection_521](https://user-images.githubusercontent.com/201263/40687779-08b4758e-639c-11e8-8507-9a94bfe2eb31.png)
----
![selection_522](https://user-images.githubusercontent.com/201263/40687781-0cc8f19a-639c-11e8-9684-110b4fe9e3c4.png)
----

This happens because interface make an impression, that after manually typing a witness name, you still need to click it, to add a witness to list above:

![selection_524](https://user-images.githubusercontent.com/201263/40687966-a0529a60-639c-11e8-9644-7702853e921f.png)

Showing the complete list of all witnesses, solves all of those issues. If we want to have the network with best witnesses we should not make this __artificially__ harder for new or smaller witnesses.

And I am saying this... even if that would mean, that better witnesses would then overcome me. If they will have equal chances and community will say they are better witnesses then I, I won't mind this.

**Comment by jamzed** [comment] 2018-05-29 22:52
Completely agree, the current voting page isn't clear enough for many Steemians, and vote/unvote situation happens very often. I would also love to see a little more witness details on the page, for example, if the witness is updating the price feed, or what is the ratio of produced blocks to the missed blocks, something that help people make a good choice.

**Comment by corkyk** [comment] 2018-05-30 00:07
I debated this with @TimCliff once before and will do so again on an upcoming radio broadcast (im not gonna plug it directly here and we plan to set a scheduled date for it tomorrow when he is being interviewed on another show on my network) Watch my blog for that. 

There are now easily 200+ witnesses that are generally mostly active or on their way to their first block or "coming back" from missed blocks, and some who havent been seen in quite some time. Including one on the top 50 list who has published a resignation months ago now, but remains on the voting roster that the entire public is funnelled to. I was challenged to submit this change request by tim AGAIN, who said "I blocked it the first time, but if it was represented I wouldn't try to stop it, however I would present my disagreement with it" To find out why, come to our debate when I take him to task on that remark from one of our last large public witness forums.

How can people vote for the candidates if they don't know who they are? And I won't accept any excuse that they should somehow accidentally discover them on their own, that's just silly and smells of fear. 

Our two person team is currently witness 63 and I will fight for this visibility and clear data on who is active and who isnt for our users, even if by some miracle I became #50, #20 or #1. For one thing, I want the best witnesses in charge even if if ISNT our team, and for another, it's just silly NOT to show the public how strong the chain is and how many nodes exist. If I were an investor and I thought only 50 people ran this place, I'd run like hell. Knowing 200ish have a shot at a meritocracy based level of influence makes me a LOT more comfortable with the platform. I can go on all day about why this SHOULD happen and why anyone trying to stop it is simply afraid. Call a spade a spade.

**Comment by corkyk** [comment] 2018-05-30 00:10
@roadscape thanks for reopening this and applying the help wanted tag. I'll take a look at the code and see if I can find where to change 20 to 200 and perhaps cross over to the PR from @netuoso to color the inactive witnesses accordingly as well, rejected apparently because his one or two lines of css had some alleged issue? Which smells funny to me, if nobody can work out how to turn black text red and add a tool tip to em. I know netty can do that, so something tells me it got shut down because again, it opens up more voter awareness and threatens incumbents.

Call me a tinfoil hat conspiracy theorist all day, there is no other logical explanation for these denials., its occam's razor here as far as it looks to most of the witnesses Ive talked to who are not AGAINST the idea..

**Comment by nnnarvaez** [comment] 2018-05-30 02:00
I would agree people should not vote for witnesses when they don't know who they are. 

This is why the main interface should present the user with a complete list so they can have as an official reference when choosing their witnesses.

**Comment by TimCliff** [comment] 2018-05-30 02:29
Two things to add:

The "voting/unvoting" issue is unrelated. It happens to everyone regardless of their position:
![image](https://user-images.githubusercontent.com/20735105/40695497-080ef772-6387-11e8-9902-09114897ed6e.png)
It is caused by https://github.com/steemit/condenser/issues/1610 . It would be really great if this could be fixed too! (but it is unrelated to this thread)

If the page is expanded to more than 50 witnesses, it will become more important to distinguish between 'active' and 'inactive' witnesses as @corkyk mentioned. Along with this, there really should be a way to educate users who are viewing the witness page what an 'active' vs. 'inactive' witness is.

**Comment by X40L1N** [comment] 2018-05-30 02:46
Why not drop that witness page altogether and implement @Jolly-Pirate (@drakos) Steemian.info site as a reference point. He will be top 20 soon and for good reason. Wouldn't it be as simple as a redirect once someone went to the (~witnesses) url? The answer is already staring us in the face if you ask me. It already defines dead witnesses, gives links to all their profiles, and a bunch of other great information including a voting tab specific to that witness so there is no confusion if a person would choose to add a witness to their respective lists. 

-Witty

**Comment by corkyk** [comment] 2018-05-30 03:39
"educate users who are viewing the witness page what an 'active' vs. 'inactive' witness is."

That's why I added tooltips in my concept remarks above. Given we wont get much new UI here, we can extend the list, color the inactives as per nettys PR that got denied on css stuff, and use a hover over tool tip on inactives to explain it in 20 words or less

**Comment by corkyk** [comment] 2018-05-30 03:42
I am 100% for @X40L1N suggestion to use @Jolly-Pirate page too, its built, has faqs, addtl features we arent even tabling here. Question would remain, is steemit inc married to hosting the page and if so, WHY?

**Comment by quochuy** [comment] 2018-05-30 04:10
I'd also like the witness_update command to also include a description of what a witness does and this info should be made available on the witnesses page. A kind of teaser before end users even go and click to see the witness announcement post.

**Comment by propertunist** [comment] 2018-05-30 05:11
I already opened an issue via utopian with an improved page design that includes what is being asked for here: https://steemit.com/utopian-io/@ura-soul/suggestion-improved-witness-voting-page-for-steemit-com

![](https://cdn.steemitimages.com/0x0/https://res.cloudinary.com/hpiynhbhq/image/upload/v1521943084/qjbfoxbhvtvo4yxiejtt.jpg)

**Comment by noisy** [comment] 2018-05-30 05:56
> Why not drop that witness page altogether and implement @Jolly-Pirate (@drakos) Steemian.info site as a reference point.

I totally understand this argument, but I do not believe, that Steemit Inc. would like to (in this very important case) just redirect to another website, without making sure, that it will be always available. 

Sure... Steemit Inc. could host it, but even then that would introduce as a dependency a SteemConnect, which is needed to vote for witnesses from Steemian.info.

Yes... in theory Steemian.info could be refactored, so it could be integrated with steemit.com, so it would not require SteemConnect, but all of that are additional steps, which IMO should be avoided if much simpler solution could provide core value which is described earlier: equal visibility to all witnesses.

Extending a list would be like a `fix` for current broken situation, where better page (more informative), would be like an `improvement`. I am just afraid, that if we would like to do too much at once, then that would delay actual fix for current situation.

**Comment by roadscape** [comment] 2018-05-30 17:13
steem PR for `/~witnesses` to return top 100:
https://github.com/steemit/steem/pull/2516

condenser PR to show witness disabled state/duration:
https://github.com/steemit/condenser/pull/2828

**Comment by Felander-steem** [comment] 2018-05-31 10:59
Well this is a step in the right direction...

this will make another 38 available for the general publick to vote on but will also activate 12 dead witnesses to be available for votes that are useless.  then one of the big issues would be to indeed signalling who is active and who is not.  I really think this is crucial.  (this is coming from a witness that would not be in either lists.)

**Comment by KINGdotNET** [comment] 2018-05-31 11:04
Thanks for the update @roadscape. I will apply this to my condenser, showing 200 witnesses instead.

**Comment by noisy** [comment] 2018-05-31 11:31
> Well this is a step in the right direction...
exactly...

> showing 200 witnesses instead.

@roadscape my question is, how code would behave if we would put there a number, which is greater then a current number of witnesses? Like for example a 1000 or 10 000?

One more time, I really appreciate changing 50 to 100, but this is still not something what I would name "equal visibility" for all witnesses.

there is a reason why I wrote my comment in an issue with name
> Show the **complete** list of witnesses on steemit.com/~witnesses 

:)

**Comment by quochuy** [comment] 2018-05-31 12:06
Yes @roadscape. Why just 100? We currently have 136 active witnesses.

**Comment by cryptohazard** [comment] 2018-05-31 12:40
something like: https://steemian.info/witnesses would be nice.

**Comment by corkyk** [comment] 2018-05-31 12:48
@cryptohazard you should scan above please.

As for the rest, complete is the recurring request here, why are we only going halfway?

**Comment by roadscape** [comment] 2018-05-31 13:14
The top 50 are decently tidy but top 100 reveals many stale/dead witnesses. Beyond this returns diminish.

These PRs propose to double the number of shown witnesses and to include more information about disabled state. The condenser PR was based off @netuoso’s branch which appears to have the voting glitch fixed as well.

I suspect this combination of changes will help drive the quality of witness votes. I propose we observe the results and then discuss further changes.

**Comment by X40L1N** [comment] 2018-05-31 18:11
Fair enough @roadscape , thanks for compromising.

**Comment by SomethingSubtle** [comment] 2018-05-31 20:39
Is there a way to remove stale/dead witnesses from the list and still provide a solution that will scale to hundreds of witnesses? 

I think this is a worthwhile change to make witnesses more obvious to users.

**Comment by corkyk** [comment] 2018-05-31 20:54
> Is there a way to remove stale/dead witnesses from the list and still provide a solution that will scale to hundreds of witnesses?

It would not be optimal to do that because there are a ton of legitimate reasons for a witness to be temporarily inactive, and most I have discussed this with agree it's legit to keep showing them, for some amount of time. 

I have discussed a proposition with many other witnesses though, to consider removing them after say, 90 days, allowing for upgrades, maintenance, temporary glitches, and stuff like failing to pay your host and needing time to fix that and things. I feel by 60-90 days though, if you aren't back, you should be considered effectively gone. This however, leads to needing to talk about returning votes to users when this witness is disqualified and that's not a topic for this thread. Further, discussions have occurred around vote decay, which would lead to a need for vote reconsideration and renewal by users. This however, usually leads to discussions about the fact that less than 1/3 of the platform has ever even voted the FIRST time (or at all ever basically) and that too is not a topic for this thread. Anyway ,I have yet to find other than anecdotal agreement to these ideas and not enough surety of an acceptable plan to submit a suggestion or PR on it.

**Comment by corkyk** [comment] 2018-05-31 21:14
@roadscape my last comment leads me to believe that if the merges are done, i propose we should probably close this one back up and start new threads for these other ideas.

**Comment by roadscape** [comment] 2018-06-01 16:13
Sounds good, thanks 👍

**Closed by roadscape** 2018-06-01 16:13 UTC
Labels: help-wanted

**Comment by noisy** [comment] 2018-07-07 00:50
Listing "100 witnesses" is now deployed on Steemit. I believe that this is now time, to reopened this issue again, to make sure, that now... this will be implemented in a proper and final way - list all witnesses (even those from last places)

After all name of this issue is one more time:
> Show the **complete list** of witnesses on steemit.com/~witnesses

CC: @roadscape

**Comment by Jolly-Pirate** [comment] 2018-07-07 02:31
Listing all witnesses might be too much, most of the ones below rank 150 are inactive or old miners. I think top 100 is a good compromise.

**Comment by KINGdotNET** [comment] 2018-07-07 02:48
I disagree. If not all, 300 max listing should be appropriate.

Thank you,
Emil

---
KING.NET - Ideas to Life | Network of Innovation
QUE.COM - Game Studio
MAJ.COM - Management of Assets and Joint Venture.
============================
[PROPRIETARY AND CONFIDENTIAL]
The information contained within this email (including any attachments) is considered confidential information intended only for the use of the individual or entity named. If the reader of the message is not the intended recipient, you are hereby notified that any unauthorized review, copy, disclosure, or distribution of this communication is strictly prohibited. If you received this email message in error, please immediately notify the sender by reply email and delete this message, and any attachments from your system. Thank you for your cooperation. 
============================ 
Acknowledgement.com - Word of Wisdom
---

**Comment by noisy** [comment] 2018-07-21 14:08
@Jolly-Pirate 

I don't care inactive witnesses... but I care about fresh blood. There are new witnesses which want to join the race, and deserve to be a witnesses more than a few witnesses in top50, which are inactive on Steem for few months in a row.

For example @steempress become a witness Yesterday, and right now they are far bellow 100 position. They are creating great product for all community, but voting for them right now is... much more difficult than for others.

**Comment by TimCliff** [comment] 2018-07-21 18:58
I don’t know if a comparison with US politics is valid, but in the US anyone (who meets the legal requirements) is allowed to run for president. Just because someone is running though does not guarantee that they will show up on the ballot. Many candidates are “write ins”. A candidate needs to demonstrate that they have achieved a certain level of support on their own before they are added to the ballot. In my view this is a reasonable expectation for witness candidates as well.

**Comment by Jolly-Pirate** [comment] 2018-07-21 21:10
We all started from the bottom and worked hard to the way up. New witnesses shouldn't expect to get high overnight. They need to prove themselves to the rest of the community and that takes time.

**Comment by noisy** [comment] 2018-07-24 05:48
> New witnesses shouldn't expect to climb high overnight. 

this is in the best interest of whole Steem community to make being a witness as competitive as possible.

If some "old witness" despite having huge early advantage, massive experience and knowledge from few years... will be lower in rank than a new witness... only because both could be voted with the same interface...

then "old witness" is simply not providing a value for a community.... or in general DPOS doesn't make sense.

> New witnesses shouldn't expect to climb high overnight.

Old witnesses shouldn't expect to preserve status quo just because they were first.
