### ISSUE TITLE
Request for feature: Frozen tags and links on feed page of steemit

### ISSUE THREAD

**Issue by shreyasgune1** [steemit/condenser#1898] opened 2017-10-31 18:44 UTC
This post is to request the features of frozen tags and links on feed page of *steemit*.

The present feeds page of *steemit* looks like this:

![Screen Shot 2017-10-31 at 5.19.19 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509450593/e1kcsn4xeffo7owm6xhu.png)

When we scroll down a little, tags and links list on both sides of main feed are no longer visible.  

![Screen Shot 2017-10-31 at 5.21.06 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509450689/wyryebronjzc67esiu3m.png)

I request that the tags and link option be frozen so that it is available even after scrolling down. I have shown how it would look like in the pic below:

![Screen Shot 2017-10-31 at 5.21.06 PM.png](https://res.cloudinary.com/hpiynhbhq/image/upload/v1509450985/gzmwygd9hywjvjzw8fhl.png)

## Advantages

1. Tags and Link will be accessible even after scrolling down.
2. This will improve the UI drastically.
3. Overall look and feel of *steemit* website will improve.
4. It can be very easily done without requiring drastic changes in the code.
5. Steemit web app will become more responsive.
5. Better user engagement.

<br /><hr/><em>Open Source Contribution posted via <a href="https://utopian.io/utopian-io/@shreyasgune/request-for-feature-frozen-tags-and-links-on-feed-page-of-steemit">Utopian.io</a></em><hr/>

**Comment by plink01001** [comment] 2017-11-16 02:37
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:37 UTC
Labels: enhancement-review
