### ISSUE TITLE
Updated Follow Button Location

### ISSUE THREAD

**Issue by TimCliff** [steemit/condenser#402] opened 2016-10-04 00:41 UTC
A more visible follow button, with the same style as the promote button, making it easier to follow user's instead of having to click the drop down menu from their name. (suggestion from dahaz159)

**Comment by plink01001** [comment] 2017-11-14 03:21
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:21 UTC
Labels: enhancement-review, feature-request, nicetohave, small+quick win, UI
