### ISSUE TITLE
Error on "Estimated Account Value" in wallet

### ISSUE THREAD

**Issue by Victorier7** [steemit/condenser#3102] opened 2018-11-23 01:51 UTC
I find the "Estimated Account Value" in wallet seems have some calculation error just now. Please kindly find my post below for some screen capture as reference, as not sure how to upload picture in here:
https://steemit.com/utopian-io/@victorier/becoming-millionaire-or-error-found

Thanks for your notice.

**Comment by TimCliff** [comment] 2018-11-23 01:57
Dupe of https://github.com/steemit/condenser/issues/3101

**Closed** 2019-04-23 20:12 UTC
Labels: bug
