### ISSUE TITLE
Increase character limit for user "Display Name" to accommodate longer names

### ISSUE THREAD

**Issue by imwatsi** [steemit/condenser#1858] opened 2017-10-26 15:38 UTC
My full name requires 22 characters and the limit doesn't allow me to put my full name in. Perhaps you could increase the character limit a bit to accommodate people with longer full names. There are probably a lot of people with longer names who will be using Steemit in the future as we push for mainstream adoption.

Thanks.

**Comment by plink01001** [comment] 2017-11-16 02:26
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-16 02:26 UTC
Labels: enhancement-review
