### ISSUE TITLE
Follow Posts Feature

### ISSUE THREAD

**Issue by KrNel** [steemit/condenser#679] opened 2016-11-20 15:12 UTC
Hello devs,

Follow Posts is an option to receive notifications on comments done to a post, either because you commented yourself, or even without commenting you could optionally choose to "Watch" or "Follow" a post's activity. There is also the option to "unfollow" toggled within the post. Currently only replies to your own comments/posts are notified. We don't have the option to be alerted of other activity on the post.

It could even be done automatically with an "upvote", with the option to remove the "Follow" or "Watch" on the post, but that might be too much. 

This feature will greatly impact interconnectivity in the social network aspect of Steemit. Users will be able to interact with other commenters, and the author, by seeing what is continually being added to a post that has content they are more interested in. Commenting will increase by some factor, and help increase activity on Steemit overall.

Thank you for this consideration and great work. I looked up "open" and "closed" issues, but did not see one for this feature.

Peace.

**Comment by plink01001** [comment] 2017-11-14 03:22
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-14 03:22 UTC
Labels: enhancement-review, feature-request, notifications
