### ISSUE TITLE
Getting mention notifications from muted accounts

### ISSUE THREAD

**Issue by steevc** [steemit/condenser#1987] opened 2017-11-14 10:34 UTC
At least in Chrome on Android I get notifications of being mentioned even though I have muted that account. I'm not interested in the 'top posts for tag' type posts. If I've muted someone then I don't want any notifications for anything they do.

Notifications are generally erratic, but that's another issue and I know a new system is being worked on. I expect big accounts will get overwhelmed with notifications and will need filters to manage them. Someone like Ned must get mentioned hundreds of times each day.

**Comment by sneak** [comment] 2017-11-14 13:58
The current notifications system has a lot of issues and is being replaced. This is actually a feature request; it isn’t in our 2.0 of notifications but will be shortly thereafter. Leaving this open to track the addition of the feature. (this actually belongs in the steemit/yo repo).

**Comment by steevc** [comment] 2017-11-14 16:24
Fair enough. Just reporting a current issue that others may encounter. Looking forward to seeing the planned enhanced features

**Comment by TimCliff** [comment] 2017-11-14 18:24
This is actually a duplicate of https://github.com/steemit/condenser/issues/1114

**Comment by plink01001** [comment] 2017-11-16 03:10
Closing duplicate

**Closed by plink01001** 2017-11-16 03:10 UTC
