### ISSUE TITLE
provide back button after navigating away from homepage

### ISSUE THREAD

**Issue by bnchdrff** [steemit/condenser#2047] opened 2017-11-23 14:47 UTC
this continues the discussion started in #1639 

@pkattera commented:

> For users coming to an article page from the home page, I'd prefer to keep the normal navigation structure in place, with the addition of a back button 'icon'. 
> 
> If the user hits the back icon or the logo from the article page, they should be returned to the home page at the previous scroll position.
> 
> <img width="536" alt="32857069-b15f81d2-ca14-11e7-8a05-ebab7ec058e3" src="https://user-images.githubusercontent.com/1121139/33143478-f85b3cfc-cf87-11e7-982c-6ed659a49e99.png">
>

**Comment by plink01001** [comment] 2017-11-28 02:25
Closing duplicate of https://github.com/steemit/condenser/issues/1998

**Closed by plink01001** 2017-11-28 02:25 UTC
