### ISSUE TITLE
/tags page has been broken for as long as I can remember.

### ISSUE THREAD

**Issue by Transisto** [steemit/condenser#1578] opened 2017-07-20 19:21 UTC
![image](https://user-images.githubusercontent.com/388716/28434895-1767111a-6d5f-11e7-9f70-81a3bc63b4d9.png)

**Comment by roadscape** [comment] 2017-07-20 19:51
Dupe of https://github.com/steemit/condenser/issues/1302

**Closed by roadscape** 2017-07-20 19:51 UTC
