### ISSUE TITLE
Add option to toggle vote sliders in the Settings page

### ISSUE THREAD

**Issue by pfunks** [steemit/condenser#1258] opened 2017-03-23 02:56 UTC
When the vote slider was implemented, there was no Settings page. Instead it was granted to accounts past a certain threshold of VESTS. This has not changed since. 

Two steps to voting increases cognitive load which should be minimized. To reduce voting cognitive load, especially for owners of lower-staked accounts:  Make the slider default to off, and give the option to all accounts to turn it on. This way those that have the need will be able to use it, and those that don't will have one less click and less thinking between them and voting.

**Comment by TimCliff** [comment] 2017-07-22 05:35
For users with low SP, if they enable the slider they will likely hit the dust limit for voting and get an error. Is this acceptable? Otherwise, to properly implement the change the logic for the slider may need to become more intelligent.

**Comment by TimCliff** [comment] 2017-08-10 02:16
discussed with sneak, and the setting should only be visible in the settings if the user has enough SP to use the slider.

**Comment by plink01001** [comment] 2017-11-15 03:54
Thank you for the suggestion. We have reviewed your request and will consider implementing it at a later point in time. For now, the issue has been closed and moved to the `enhancement-review` category. These issues are being reviewed and considered for future development, but are not actively being worked on at this time. We may re-open the issue at a later date, if/when it is ready to be assigned to a developer.  We encourage users to open issues that pertain specifically to bugs or existing functionality that does not work correctly or as intended. If you have additional enhancement suggestions, please make them by following the steps in the [Guidelines for Contributing](https://github.com/steemit/condenser/blob/master/CONTRIBUTING.md).

**Closed by plink01001** 2017-11-15 03:54 UTC
Labels: enhancement-review, feature-request
